std_msgs/Header header

float32[7] dot_qr
float32[7] ddot_qr
float32[7] s
float32[42] J
float32[42] J_dot
float32[42] J_pinv
float32[9] L
float32[36] conv0
float32[36] conv1
float32[36] conv2

link_params link1
link_params link2
link_params link3
link_params link4
link_params link5
link_params link6
link_params link7

float32[7] Yr_param
float32[7] tau_cmd
float32[7] tau_tilde

float32[6] error_pos_EE
float32[6] dot_error_pos_EE