/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int frankino_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_C_fun_alloc_mem(void);
extern "C" int frankino_C_fun_init_mem(int mem);
extern "C" void frankino_C_fun_free_mem(int mem);
extern "C" int frankino_C_fun_checkout(void);
extern "C" void frankino_C_fun_release(int mem);
extern "C" void frankino_C_fun_incref(void);
extern "C" void frankino_C_fun_decref(void);
extern "C" casadi_int frankino_C_fun_n_in(void);
extern "C" casadi_int frankino_C_fun_n_out(void);
extern "C" casadi_real frankino_C_fun_default_in(casadi_int i);
extern "C" const char* frankino_C_fun_name_in(casadi_int i);
extern "C" const char* frankino_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_C_fun_sparsity_out(casadi_int i);
extern "C" int frankino_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_C_fun_SZ_ARG 2
#define frankino_C_fun_SZ_RES 1
#define frankino_C_fun_SZ_IW 0
#define frankino_C_fun_SZ_W 0
extern "C" int frankino_C_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_C_ddot_fun_alloc_mem(void);
extern "C" int frankino_C_ddot_fun_init_mem(int mem);
extern "C" void frankino_C_ddot_fun_free_mem(int mem);
extern "C" int frankino_C_ddot_fun_checkout(void);
extern "C" void frankino_C_ddot_fun_release(int mem);
extern "C" void frankino_C_ddot_fun_incref(void);
extern "C" void frankino_C_ddot_fun_decref(void);
extern "C" casadi_int frankino_C_ddot_fun_n_in(void);
extern "C" casadi_int frankino_C_ddot_fun_n_out(void);
extern "C" casadi_real frankino_C_ddot_fun_default_in(casadi_int i);
extern "C" const char* frankino_C_ddot_fun_name_in(casadi_int i);
extern "C" const char* frankino_C_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_C_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_C_ddot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_C_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_C_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_C_ddot_fun_SZ_ARG 4
#define frankino_C_ddot_fun_SZ_RES 1
#define frankino_C_ddot_fun_SZ_IW 0
#define frankino_C_ddot_fun_SZ_W 0
extern "C" int frankino_C_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_C_dot_fun_alloc_mem(void);
extern "C" int frankino_C_dot_fun_init_mem(int mem);
extern "C" void frankino_C_dot_fun_free_mem(int mem);
extern "C" int frankino_C_dot_fun_checkout(void);
extern "C" void frankino_C_dot_fun_release(int mem);
extern "C" void frankino_C_dot_fun_incref(void);
extern "C" void frankino_C_dot_fun_decref(void);
extern "C" casadi_int frankino_C_dot_fun_n_in(void);
extern "C" casadi_int frankino_C_dot_fun_n_out(void);
extern "C" casadi_real frankino_C_dot_fun_default_in(casadi_int i);
extern "C" const char* frankino_C_dot_fun_name_in(casadi_int i);
extern "C" const char* frankino_C_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_C_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_C_dot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_C_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_C_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_C_dot_fun_SZ_ARG 3
#define frankino_C_dot_fun_SZ_RES 1
#define frankino_C_dot_fun_SZ_IW 0
#define frankino_C_dot_fun_SZ_W 0
extern "C" int frankino_C_std_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_C_std_fun_alloc_mem(void);
extern "C" int frankino_C_std_fun_init_mem(int mem);
extern "C" void frankino_C_std_fun_free_mem(int mem);
extern "C" int frankino_C_std_fun_checkout(void);
extern "C" void frankino_C_std_fun_release(int mem);
extern "C" void frankino_C_std_fun_incref(void);
extern "C" void frankino_C_std_fun_decref(void);
extern "C" casadi_int frankino_C_std_fun_n_in(void);
extern "C" casadi_int frankino_C_std_fun_n_out(void);
extern "C" casadi_real frankino_C_std_fun_default_in(casadi_int i);
extern "C" const char* frankino_C_std_fun_name_in(casadi_int i);
extern "C" const char* frankino_C_std_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_C_std_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_C_std_fun_sparsity_out(casadi_int i);
extern "C" int frankino_C_std_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_C_std_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_C_std_fun_SZ_ARG 2
#define frankino_C_std_fun_SZ_RES 1
#define frankino_C_std_fun_SZ_IW 0
#define frankino_C_std_fun_SZ_W 0
extern "C" int frankino_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_G_fun_alloc_mem(void);
extern "C" int frankino_G_fun_init_mem(int mem);
extern "C" void frankino_G_fun_free_mem(int mem);
extern "C" int frankino_G_fun_checkout(void);
extern "C" void frankino_G_fun_release(int mem);
extern "C" void frankino_G_fun_incref(void);
extern "C" void frankino_G_fun_decref(void);
extern "C" casadi_int frankino_G_fun_n_in(void);
extern "C" casadi_int frankino_G_fun_n_out(void);
extern "C" casadi_real frankino_G_fun_default_in(casadi_int i);
extern "C" const char* frankino_G_fun_name_in(casadi_int i);
extern "C" const char* frankino_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_G_fun_sparsity_out(casadi_int i);
extern "C" int frankino_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_G_fun_SZ_ARG 1
#define frankino_G_fun_SZ_RES 1
#define frankino_G_fun_SZ_IW 0
#define frankino_G_fun_SZ_W 0
extern "C" int frankino_G_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_G_ddot_fun_alloc_mem(void);
extern "C" int frankino_G_ddot_fun_init_mem(int mem);
extern "C" void frankino_G_ddot_fun_free_mem(int mem);
extern "C" int frankino_G_ddot_fun_checkout(void);
extern "C" void frankino_G_ddot_fun_release(int mem);
extern "C" void frankino_G_ddot_fun_incref(void);
extern "C" void frankino_G_ddot_fun_decref(void);
extern "C" casadi_int frankino_G_ddot_fun_n_in(void);
extern "C" casadi_int frankino_G_ddot_fun_n_out(void);
extern "C" casadi_real frankino_G_ddot_fun_default_in(casadi_int i);
extern "C" const char* frankino_G_ddot_fun_name_in(casadi_int i);
extern "C" const char* frankino_G_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_G_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_G_ddot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_G_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_G_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_G_ddot_fun_SZ_ARG 3
#define frankino_G_ddot_fun_SZ_RES 1
#define frankino_G_ddot_fun_SZ_IW 0
#define frankino_G_ddot_fun_SZ_W 0
extern "C" int frankino_G_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_G_dot_fun_alloc_mem(void);
extern "C" int frankino_G_dot_fun_init_mem(int mem);
extern "C" void frankino_G_dot_fun_free_mem(int mem);
extern "C" int frankino_G_dot_fun_checkout(void);
extern "C" void frankino_G_dot_fun_release(int mem);
extern "C" void frankino_G_dot_fun_incref(void);
extern "C" void frankino_G_dot_fun_decref(void);
extern "C" casadi_int frankino_G_dot_fun_n_in(void);
extern "C" casadi_int frankino_G_dot_fun_n_out(void);
extern "C" casadi_real frankino_G_dot_fun_default_in(casadi_int i);
extern "C" const char* frankino_G_dot_fun_name_in(casadi_int i);
extern "C" const char* frankino_G_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_G_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_G_dot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_G_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_G_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_G_dot_fun_SZ_ARG 2
#define frankino_G_dot_fun_SZ_RES 1
#define frankino_G_dot_fun_SZ_IW 0
#define frankino_G_dot_fun_SZ_W 0
extern "C" int frankino_J_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_1_fun_alloc_mem(void);
extern "C" int frankino_J_1_fun_init_mem(int mem);
extern "C" void frankino_J_1_fun_free_mem(int mem);
extern "C" int frankino_J_1_fun_checkout(void);
extern "C" void frankino_J_1_fun_release(int mem);
extern "C" void frankino_J_1_fun_incref(void);
extern "C" void frankino_J_1_fun_decref(void);
extern "C" casadi_int frankino_J_1_fun_n_in(void);
extern "C" casadi_int frankino_J_1_fun_n_out(void);
extern "C" casadi_real frankino_J_1_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_1_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_1_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_1_fun_SZ_ARG 1
#define frankino_J_1_fun_SZ_RES 1
#define frankino_J_1_fun_SZ_IW 0
#define frankino_J_1_fun_SZ_W 0
extern "C" int frankino_J_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_2_fun_alloc_mem(void);
extern "C" int frankino_J_2_fun_init_mem(int mem);
extern "C" void frankino_J_2_fun_free_mem(int mem);
extern "C" int frankino_J_2_fun_checkout(void);
extern "C" void frankino_J_2_fun_release(int mem);
extern "C" void frankino_J_2_fun_incref(void);
extern "C" void frankino_J_2_fun_decref(void);
extern "C" casadi_int frankino_J_2_fun_n_in(void);
extern "C" casadi_int frankino_J_2_fun_n_out(void);
extern "C" casadi_real frankino_J_2_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_2_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_2_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_2_fun_SZ_ARG 1
#define frankino_J_2_fun_SZ_RES 1
#define frankino_J_2_fun_SZ_IW 0
#define frankino_J_2_fun_SZ_W 0
extern "C" int frankino_J_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_3_fun_alloc_mem(void);
extern "C" int frankino_J_3_fun_init_mem(int mem);
extern "C" void frankino_J_3_fun_free_mem(int mem);
extern "C" int frankino_J_3_fun_checkout(void);
extern "C" void frankino_J_3_fun_release(int mem);
extern "C" void frankino_J_3_fun_incref(void);
extern "C" void frankino_J_3_fun_decref(void);
extern "C" casadi_int frankino_J_3_fun_n_in(void);
extern "C" casadi_int frankino_J_3_fun_n_out(void);
extern "C" casadi_real frankino_J_3_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_3_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_3_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_3_fun_SZ_ARG 1
#define frankino_J_3_fun_SZ_RES 1
#define frankino_J_3_fun_SZ_IW 0
#define frankino_J_3_fun_SZ_W 0
extern "C" int frankino_J_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_4_fun_alloc_mem(void);
extern "C" int frankino_J_4_fun_init_mem(int mem);
extern "C" void frankino_J_4_fun_free_mem(int mem);
extern "C" int frankino_J_4_fun_checkout(void);
extern "C" void frankino_J_4_fun_release(int mem);
extern "C" void frankino_J_4_fun_incref(void);
extern "C" void frankino_J_4_fun_decref(void);
extern "C" casadi_int frankino_J_4_fun_n_in(void);
extern "C" casadi_int frankino_J_4_fun_n_out(void);
extern "C" casadi_real frankino_J_4_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_4_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_4_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_4_fun_SZ_ARG 1
#define frankino_J_4_fun_SZ_RES 1
#define frankino_J_4_fun_SZ_IW 0
#define frankino_J_4_fun_SZ_W 0
extern "C" int frankino_J_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_5_fun_alloc_mem(void);
extern "C" int frankino_J_5_fun_init_mem(int mem);
extern "C" void frankino_J_5_fun_free_mem(int mem);
extern "C" int frankino_J_5_fun_checkout(void);
extern "C" void frankino_J_5_fun_release(int mem);
extern "C" void frankino_J_5_fun_incref(void);
extern "C" void frankino_J_5_fun_decref(void);
extern "C" casadi_int frankino_J_5_fun_n_in(void);
extern "C" casadi_int frankino_J_5_fun_n_out(void);
extern "C" casadi_real frankino_J_5_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_5_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_5_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_5_fun_SZ_ARG 1
#define frankino_J_5_fun_SZ_RES 1
#define frankino_J_5_fun_SZ_IW 0
#define frankino_J_5_fun_SZ_W 0
extern "C" int frankino_J_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_6_fun_alloc_mem(void);
extern "C" int frankino_J_6_fun_init_mem(int mem);
extern "C" void frankino_J_6_fun_free_mem(int mem);
extern "C" int frankino_J_6_fun_checkout(void);
extern "C" void frankino_J_6_fun_release(int mem);
extern "C" void frankino_J_6_fun_incref(void);
extern "C" void frankino_J_6_fun_decref(void);
extern "C" casadi_int frankino_J_6_fun_n_in(void);
extern "C" casadi_int frankino_J_6_fun_n_out(void);
extern "C" casadi_real frankino_J_6_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_6_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_6_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_6_fun_SZ_ARG 1
#define frankino_J_6_fun_SZ_RES 1
#define frankino_J_6_fun_SZ_IW 0
#define frankino_J_6_fun_SZ_W 0
extern "C" int frankino_J_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_7_fun_alloc_mem(void);
extern "C" int frankino_J_7_fun_init_mem(int mem);
extern "C" void frankino_J_7_fun_free_mem(int mem);
extern "C" int frankino_J_7_fun_checkout(void);
extern "C" void frankino_J_7_fun_release(int mem);
extern "C" void frankino_J_7_fun_incref(void);
extern "C" void frankino_J_7_fun_decref(void);
extern "C" casadi_int frankino_J_7_fun_n_in(void);
extern "C" casadi_int frankino_J_7_fun_n_out(void);
extern "C" casadi_real frankino_J_7_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_7_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_7_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_7_fun_SZ_ARG 1
#define frankino_J_7_fun_SZ_RES 1
#define frankino_J_7_fun_SZ_IW 0
#define frankino_J_7_fun_SZ_W 0
extern "C" int frankino_J_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_8_fun_alloc_mem(void);
extern "C" int frankino_J_8_fun_init_mem(int mem);
extern "C" void frankino_J_8_fun_free_mem(int mem);
extern "C" int frankino_J_8_fun_checkout(void);
extern "C" void frankino_J_8_fun_release(int mem);
extern "C" void frankino_J_8_fun_incref(void);
extern "C" void frankino_J_8_fun_decref(void);
extern "C" casadi_int frankino_J_8_fun_n_in(void);
extern "C" casadi_int frankino_J_8_fun_n_out(void);
extern "C" casadi_real frankino_J_8_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_8_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_8_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_8_fun_SZ_ARG 1
#define frankino_J_8_fun_SZ_RES 1
#define frankino_J_8_fun_SZ_IW 0
#define frankino_J_8_fun_SZ_W 0
extern "C" int frankino_J_cm_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_1_fun_alloc_mem(void);
extern "C" int frankino_J_cm_1_fun_init_mem(int mem);
extern "C" void frankino_J_cm_1_fun_free_mem(int mem);
extern "C" int frankino_J_cm_1_fun_checkout(void);
extern "C" void frankino_J_cm_1_fun_release(int mem);
extern "C" void frankino_J_cm_1_fun_incref(void);
extern "C" void frankino_J_cm_1_fun_decref(void);
extern "C" casadi_int frankino_J_cm_1_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_1_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_1_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_1_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_1_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_1_fun_SZ_ARG 1
#define frankino_J_cm_1_fun_SZ_RES 1
#define frankino_J_cm_1_fun_SZ_IW 0
#define frankino_J_cm_1_fun_SZ_W 0
extern "C" int frankino_J_cm_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_2_fun_alloc_mem(void);
extern "C" int frankino_J_cm_2_fun_init_mem(int mem);
extern "C" void frankino_J_cm_2_fun_free_mem(int mem);
extern "C" int frankino_J_cm_2_fun_checkout(void);
extern "C" void frankino_J_cm_2_fun_release(int mem);
extern "C" void frankino_J_cm_2_fun_incref(void);
extern "C" void frankino_J_cm_2_fun_decref(void);
extern "C" casadi_int frankino_J_cm_2_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_2_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_2_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_2_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_2_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_2_fun_SZ_ARG 1
#define frankino_J_cm_2_fun_SZ_RES 1
#define frankino_J_cm_2_fun_SZ_IW 0
#define frankino_J_cm_2_fun_SZ_W 0
extern "C" int frankino_J_cm_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_3_fun_alloc_mem(void);
extern "C" int frankino_J_cm_3_fun_init_mem(int mem);
extern "C" void frankino_J_cm_3_fun_free_mem(int mem);
extern "C" int frankino_J_cm_3_fun_checkout(void);
extern "C" void frankino_J_cm_3_fun_release(int mem);
extern "C" void frankino_J_cm_3_fun_incref(void);
extern "C" void frankino_J_cm_3_fun_decref(void);
extern "C" casadi_int frankino_J_cm_3_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_3_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_3_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_3_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_3_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_3_fun_SZ_ARG 1
#define frankino_J_cm_3_fun_SZ_RES 1
#define frankino_J_cm_3_fun_SZ_IW 0
#define frankino_J_cm_3_fun_SZ_W 0
extern "C" int frankino_J_cm_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_4_fun_alloc_mem(void);
extern "C" int frankino_J_cm_4_fun_init_mem(int mem);
extern "C" void frankino_J_cm_4_fun_free_mem(int mem);
extern "C" int frankino_J_cm_4_fun_checkout(void);
extern "C" void frankino_J_cm_4_fun_release(int mem);
extern "C" void frankino_J_cm_4_fun_incref(void);
extern "C" void frankino_J_cm_4_fun_decref(void);
extern "C" casadi_int frankino_J_cm_4_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_4_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_4_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_4_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_4_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_4_fun_SZ_ARG 1
#define frankino_J_cm_4_fun_SZ_RES 1
#define frankino_J_cm_4_fun_SZ_IW 0
#define frankino_J_cm_4_fun_SZ_W 0
extern "C" int frankino_J_cm_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_5_fun_alloc_mem(void);
extern "C" int frankino_J_cm_5_fun_init_mem(int mem);
extern "C" void frankino_J_cm_5_fun_free_mem(int mem);
extern "C" int frankino_J_cm_5_fun_checkout(void);
extern "C" void frankino_J_cm_5_fun_release(int mem);
extern "C" void frankino_J_cm_5_fun_incref(void);
extern "C" void frankino_J_cm_5_fun_decref(void);
extern "C" casadi_int frankino_J_cm_5_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_5_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_5_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_5_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_5_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_5_fun_SZ_ARG 1
#define frankino_J_cm_5_fun_SZ_RES 1
#define frankino_J_cm_5_fun_SZ_IW 0
#define frankino_J_cm_5_fun_SZ_W 0
extern "C" int frankino_J_cm_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_6_fun_alloc_mem(void);
extern "C" int frankino_J_cm_6_fun_init_mem(int mem);
extern "C" void frankino_J_cm_6_fun_free_mem(int mem);
extern "C" int frankino_J_cm_6_fun_checkout(void);
extern "C" void frankino_J_cm_6_fun_release(int mem);
extern "C" void frankino_J_cm_6_fun_incref(void);
extern "C" void frankino_J_cm_6_fun_decref(void);
extern "C" casadi_int frankino_J_cm_6_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_6_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_6_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_6_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_6_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_6_fun_SZ_ARG 1
#define frankino_J_cm_6_fun_SZ_RES 1
#define frankino_J_cm_6_fun_SZ_IW 0
#define frankino_J_cm_6_fun_SZ_W 0
extern "C" int frankino_J_cm_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_cm_7_fun_alloc_mem(void);
extern "C" int frankino_J_cm_7_fun_init_mem(int mem);
extern "C" void frankino_J_cm_7_fun_free_mem(int mem);
extern "C" int frankino_J_cm_7_fun_checkout(void);
extern "C" void frankino_J_cm_7_fun_release(int mem);
extern "C" void frankino_J_cm_7_fun_incref(void);
extern "C" void frankino_J_cm_7_fun_decref(void);
extern "C" casadi_int frankino_J_cm_7_fun_n_in(void);
extern "C" casadi_int frankino_J_cm_7_fun_n_out(void);
extern "C" casadi_real frankino_J_cm_7_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_cm_7_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_cm_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_cm_7_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_cm_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_cm_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_cm_7_fun_SZ_ARG 1
#define frankino_J_cm_7_fun_SZ_RES 1
#define frankino_J_cm_7_fun_SZ_IW 0
#define frankino_J_cm_7_fun_SZ_W 0
extern "C" int frankino_J_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_ee_fun_alloc_mem(void);
extern "C" int frankino_J_ee_fun_init_mem(int mem);
extern "C" void frankino_J_ee_fun_free_mem(int mem);
extern "C" int frankino_J_ee_fun_checkout(void);
extern "C" void frankino_J_ee_fun_release(int mem);
extern "C" void frankino_J_ee_fun_incref(void);
extern "C" void frankino_J_ee_fun_decref(void);
extern "C" casadi_int frankino_J_ee_fun_n_in(void);
extern "C" casadi_int frankino_J_ee_fun_n_out(void);
extern "C" casadi_real frankino_J_ee_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_ee_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_ee_fun_SZ_ARG 1
#define frankino_J_ee_fun_SZ_RES 1
#define frankino_J_ee_fun_SZ_IW 0
#define frankino_J_ee_fun_SZ_W 0
extern "C" int frankino_J_ee_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_ee_ddot_fun_alloc_mem(void);
extern "C" int frankino_J_ee_ddot_fun_init_mem(int mem);
extern "C" void frankino_J_ee_ddot_fun_free_mem(int mem);
extern "C" int frankino_J_ee_ddot_fun_checkout(void);
extern "C" void frankino_J_ee_ddot_fun_release(int mem);
extern "C" void frankino_J_ee_ddot_fun_incref(void);
extern "C" void frankino_J_ee_ddot_fun_decref(void);
extern "C" casadi_int frankino_J_ee_ddot_fun_n_in(void);
extern "C" casadi_int frankino_J_ee_ddot_fun_n_out(void);
extern "C" casadi_real frankino_J_ee_ddot_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_ee_ddot_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_ee_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_ddot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_ee_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_ee_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_ee_ddot_fun_SZ_ARG 3
#define frankino_J_ee_ddot_fun_SZ_RES 1
#define frankino_J_ee_ddot_fun_SZ_IW 0
#define frankino_J_ee_ddot_fun_SZ_W 0
extern "C" int frankino_J_ee_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_ee_dot_fun_alloc_mem(void);
extern "C" int frankino_J_ee_dot_fun_init_mem(int mem);
extern "C" void frankino_J_ee_dot_fun_free_mem(int mem);
extern "C" int frankino_J_ee_dot_fun_checkout(void);
extern "C" void frankino_J_ee_dot_fun_release(int mem);
extern "C" void frankino_J_ee_dot_fun_incref(void);
extern "C" void frankino_J_ee_dot_fun_decref(void);
extern "C" casadi_int frankino_J_ee_dot_fun_n_in(void);
extern "C" casadi_int frankino_J_ee_dot_fun_n_out(void);
extern "C" casadi_real frankino_J_ee_dot_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_ee_dot_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_ee_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_dot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_ee_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_ee_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_ee_dot_fun_SZ_ARG 2
#define frankino_J_ee_dot_fun_SZ_RES 1
#define frankino_J_ee_dot_fun_SZ_IW 0
#define frankino_J_ee_dot_fun_SZ_W 0
extern "C" int frankino_J_ee_pinv_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_J_ee_pinv_fun_alloc_mem(void);
extern "C" int frankino_J_ee_pinv_fun_init_mem(int mem);
extern "C" void frankino_J_ee_pinv_fun_free_mem(int mem);
extern "C" int frankino_J_ee_pinv_fun_checkout(void);
extern "C" void frankino_J_ee_pinv_fun_release(int mem);
extern "C" void frankino_J_ee_pinv_fun_incref(void);
extern "C" void frankino_J_ee_pinv_fun_decref(void);
extern "C" casadi_int frankino_J_ee_pinv_fun_n_in(void);
extern "C" casadi_int frankino_J_ee_pinv_fun_n_out(void);
extern "C" casadi_real frankino_J_ee_pinv_fun_default_in(casadi_int i);
extern "C" const char* frankino_J_ee_pinv_fun_name_in(casadi_int i);
extern "C" const char* frankino_J_ee_pinv_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_pinv_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_J_ee_pinv_fun_sparsity_out(casadi_int i);
extern "C" int frankino_J_ee_pinv_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_J_ee_pinv_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_J_ee_pinv_fun_SZ_ARG 1
#define frankino_J_ee_pinv_fun_SZ_RES 1
#define frankino_J_ee_pinv_fun_SZ_IW 0
#define frankino_J_ee_pinv_fun_SZ_W 0
extern "C" int frankino_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_M_fun_alloc_mem(void);
extern "C" int frankino_M_fun_init_mem(int mem);
extern "C" void frankino_M_fun_free_mem(int mem);
extern "C" int frankino_M_fun_checkout(void);
extern "C" void frankino_M_fun_release(int mem);
extern "C" void frankino_M_fun_incref(void);
extern "C" void frankino_M_fun_decref(void);
extern "C" casadi_int frankino_M_fun_n_in(void);
extern "C" casadi_int frankino_M_fun_n_out(void);
extern "C" casadi_real frankino_M_fun_default_in(casadi_int i);
extern "C" const char* frankino_M_fun_name_in(casadi_int i);
extern "C" const char* frankino_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_M_fun_sparsity_out(casadi_int i);
extern "C" int frankino_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_M_fun_SZ_ARG 1
#define frankino_M_fun_SZ_RES 1
#define frankino_M_fun_SZ_IW 0
#define frankino_M_fun_SZ_W 0
extern "C" int frankino_M_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_M_ddot_fun_alloc_mem(void);
extern "C" int frankino_M_ddot_fun_init_mem(int mem);
extern "C" void frankino_M_ddot_fun_free_mem(int mem);
extern "C" int frankino_M_ddot_fun_checkout(void);
extern "C" void frankino_M_ddot_fun_release(int mem);
extern "C" void frankino_M_ddot_fun_incref(void);
extern "C" void frankino_M_ddot_fun_decref(void);
extern "C" casadi_int frankino_M_ddot_fun_n_in(void);
extern "C" casadi_int frankino_M_ddot_fun_n_out(void);
extern "C" casadi_real frankino_M_ddot_fun_default_in(casadi_int i);
extern "C" const char* frankino_M_ddot_fun_name_in(casadi_int i);
extern "C" const char* frankino_M_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_M_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_M_ddot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_M_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_M_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_M_ddot_fun_SZ_ARG 3
#define frankino_M_ddot_fun_SZ_RES 1
#define frankino_M_ddot_fun_SZ_IW 0
#define frankino_M_ddot_fun_SZ_W 0
extern "C" int frankino_M_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_M_dot_fun_alloc_mem(void);
extern "C" int frankino_M_dot_fun_init_mem(int mem);
extern "C" void frankino_M_dot_fun_free_mem(int mem);
extern "C" int frankino_M_dot_fun_checkout(void);
extern "C" void frankino_M_dot_fun_release(int mem);
extern "C" void frankino_M_dot_fun_incref(void);
extern "C" void frankino_M_dot_fun_decref(void);
extern "C" casadi_int frankino_M_dot_fun_n_in(void);
extern "C" casadi_int frankino_M_dot_fun_n_out(void);
extern "C" casadi_real frankino_M_dot_fun_default_in(casadi_int i);
extern "C" const char* frankino_M_dot_fun_name_in(casadi_int i);
extern "C" const char* frankino_M_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_M_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_M_dot_fun_sparsity_out(casadi_int i);
extern "C" int frankino_M_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_M_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_M_dot_fun_SZ_ARG 2
#define frankino_M_dot_fun_SZ_RES 1
#define frankino_M_dot_fun_SZ_IW 0
#define frankino_M_dot_fun_SZ_W 0
extern "C" int frankino_T_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_fun_alloc_mem(void);
extern "C" int frankino_T_0_fun_init_mem(int mem);
extern "C" void frankino_T_0_fun_free_mem(int mem);
extern "C" int frankino_T_0_fun_checkout(void);
extern "C" void frankino_T_0_fun_release(int mem);
extern "C" void frankino_T_0_fun_incref(void);
extern "C" void frankino_T_0_fun_decref(void);
extern "C" casadi_int frankino_T_0_fun_n_in(void);
extern "C" casadi_int frankino_T_0_fun_n_out(void);
extern "C" casadi_real frankino_T_0_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_fun_SZ_ARG 0
#define frankino_T_0_fun_SZ_RES 1
#define frankino_T_0_fun_SZ_IW 0
#define frankino_T_0_fun_SZ_W 0
extern "C" int frankino_T_0_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_0_fun_alloc_mem(void);
extern "C" int frankino_T_0_0_fun_init_mem(int mem);
extern "C" void frankino_T_0_0_fun_free_mem(int mem);
extern "C" int frankino_T_0_0_fun_checkout(void);
extern "C" void frankino_T_0_0_fun_release(int mem);
extern "C" void frankino_T_0_0_fun_incref(void);
extern "C" void frankino_T_0_0_fun_decref(void);
extern "C" casadi_int frankino_T_0_0_fun_n_in(void);
extern "C" casadi_int frankino_T_0_0_fun_n_out(void);
extern "C" casadi_real frankino_T_0_0_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_0_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_0_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_0_fun_SZ_ARG 0
#define frankino_T_0_0_fun_SZ_RES 1
#define frankino_T_0_0_fun_SZ_IW 0
#define frankino_T_0_0_fun_SZ_W 0
extern "C" int frankino_T_0_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_1_fun_alloc_mem(void);
extern "C" int frankino_T_0_1_fun_init_mem(int mem);
extern "C" void frankino_T_0_1_fun_free_mem(int mem);
extern "C" int frankino_T_0_1_fun_checkout(void);
extern "C" void frankino_T_0_1_fun_release(int mem);
extern "C" void frankino_T_0_1_fun_incref(void);
extern "C" void frankino_T_0_1_fun_decref(void);
extern "C" casadi_int frankino_T_0_1_fun_n_in(void);
extern "C" casadi_int frankino_T_0_1_fun_n_out(void);
extern "C" casadi_real frankino_T_0_1_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_1_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_1_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_1_fun_SZ_ARG 1
#define frankino_T_0_1_fun_SZ_RES 1
#define frankino_T_0_1_fun_SZ_IW 0
#define frankino_T_0_1_fun_SZ_W 0
extern "C" int frankino_T_0_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_2_fun_alloc_mem(void);
extern "C" int frankino_T_0_2_fun_init_mem(int mem);
extern "C" void frankino_T_0_2_fun_free_mem(int mem);
extern "C" int frankino_T_0_2_fun_checkout(void);
extern "C" void frankino_T_0_2_fun_release(int mem);
extern "C" void frankino_T_0_2_fun_incref(void);
extern "C" void frankino_T_0_2_fun_decref(void);
extern "C" casadi_int frankino_T_0_2_fun_n_in(void);
extern "C" casadi_int frankino_T_0_2_fun_n_out(void);
extern "C" casadi_real frankino_T_0_2_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_2_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_2_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_2_fun_SZ_ARG 1
#define frankino_T_0_2_fun_SZ_RES 1
#define frankino_T_0_2_fun_SZ_IW 0
#define frankino_T_0_2_fun_SZ_W 0
extern "C" int frankino_T_0_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_3_fun_alloc_mem(void);
extern "C" int frankino_T_0_3_fun_init_mem(int mem);
extern "C" void frankino_T_0_3_fun_free_mem(int mem);
extern "C" int frankino_T_0_3_fun_checkout(void);
extern "C" void frankino_T_0_3_fun_release(int mem);
extern "C" void frankino_T_0_3_fun_incref(void);
extern "C" void frankino_T_0_3_fun_decref(void);
extern "C" casadi_int frankino_T_0_3_fun_n_in(void);
extern "C" casadi_int frankino_T_0_3_fun_n_out(void);
extern "C" casadi_real frankino_T_0_3_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_3_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_3_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_3_fun_SZ_ARG 1
#define frankino_T_0_3_fun_SZ_RES 1
#define frankino_T_0_3_fun_SZ_IW 0
#define frankino_T_0_3_fun_SZ_W 0
extern "C" int frankino_T_0_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_4_fun_alloc_mem(void);
extern "C" int frankino_T_0_4_fun_init_mem(int mem);
extern "C" void frankino_T_0_4_fun_free_mem(int mem);
extern "C" int frankino_T_0_4_fun_checkout(void);
extern "C" void frankino_T_0_4_fun_release(int mem);
extern "C" void frankino_T_0_4_fun_incref(void);
extern "C" void frankino_T_0_4_fun_decref(void);
extern "C" casadi_int frankino_T_0_4_fun_n_in(void);
extern "C" casadi_int frankino_T_0_4_fun_n_out(void);
extern "C" casadi_real frankino_T_0_4_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_4_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_4_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_4_fun_SZ_ARG 1
#define frankino_T_0_4_fun_SZ_RES 1
#define frankino_T_0_4_fun_SZ_IW 0
#define frankino_T_0_4_fun_SZ_W 0
extern "C" int frankino_T_0_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_5_fun_alloc_mem(void);
extern "C" int frankino_T_0_5_fun_init_mem(int mem);
extern "C" void frankino_T_0_5_fun_free_mem(int mem);
extern "C" int frankino_T_0_5_fun_checkout(void);
extern "C" void frankino_T_0_5_fun_release(int mem);
extern "C" void frankino_T_0_5_fun_incref(void);
extern "C" void frankino_T_0_5_fun_decref(void);
extern "C" casadi_int frankino_T_0_5_fun_n_in(void);
extern "C" casadi_int frankino_T_0_5_fun_n_out(void);
extern "C" casadi_real frankino_T_0_5_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_5_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_5_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_5_fun_SZ_ARG 1
#define frankino_T_0_5_fun_SZ_RES 1
#define frankino_T_0_5_fun_SZ_IW 0
#define frankino_T_0_5_fun_SZ_W 0
extern "C" int frankino_T_0_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_6_fun_alloc_mem(void);
extern "C" int frankino_T_0_6_fun_init_mem(int mem);
extern "C" void frankino_T_0_6_fun_free_mem(int mem);
extern "C" int frankino_T_0_6_fun_checkout(void);
extern "C" void frankino_T_0_6_fun_release(int mem);
extern "C" void frankino_T_0_6_fun_incref(void);
extern "C" void frankino_T_0_6_fun_decref(void);
extern "C" casadi_int frankino_T_0_6_fun_n_in(void);
extern "C" casadi_int frankino_T_0_6_fun_n_out(void);
extern "C" casadi_real frankino_T_0_6_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_6_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_6_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_6_fun_SZ_ARG 1
#define frankino_T_0_6_fun_SZ_RES 1
#define frankino_T_0_6_fun_SZ_IW 0
#define frankino_T_0_6_fun_SZ_W 0
extern "C" int frankino_T_0_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_7_fun_alloc_mem(void);
extern "C" int frankino_T_0_7_fun_init_mem(int mem);
extern "C" void frankino_T_0_7_fun_free_mem(int mem);
extern "C" int frankino_T_0_7_fun_checkout(void);
extern "C" void frankino_T_0_7_fun_release(int mem);
extern "C" void frankino_T_0_7_fun_incref(void);
extern "C" void frankino_T_0_7_fun_decref(void);
extern "C" casadi_int frankino_T_0_7_fun_n_in(void);
extern "C" casadi_int frankino_T_0_7_fun_n_out(void);
extern "C" casadi_real frankino_T_0_7_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_7_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_7_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_7_fun_SZ_ARG 1
#define frankino_T_0_7_fun_SZ_RES 1
#define frankino_T_0_7_fun_SZ_IW 0
#define frankino_T_0_7_fun_SZ_W 0
extern "C" int frankino_T_0_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_8_fun_alloc_mem(void);
extern "C" int frankino_T_0_8_fun_init_mem(int mem);
extern "C" void frankino_T_0_8_fun_free_mem(int mem);
extern "C" int frankino_T_0_8_fun_checkout(void);
extern "C" void frankino_T_0_8_fun_release(int mem);
extern "C" void frankino_T_0_8_fun_incref(void);
extern "C" void frankino_T_0_8_fun_decref(void);
extern "C" casadi_int frankino_T_0_8_fun_n_in(void);
extern "C" casadi_int frankino_T_0_8_fun_n_out(void);
extern "C" casadi_real frankino_T_0_8_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_8_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_8_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_8_fun_SZ_ARG 1
#define frankino_T_0_8_fun_SZ_RES 1
#define frankino_T_0_8_fun_SZ_IW 0
#define frankino_T_0_8_fun_SZ_W 0
extern "C" int frankino_T_0_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_0_ee_fun_alloc_mem(void);
extern "C" int frankino_T_0_ee_fun_init_mem(int mem);
extern "C" void frankino_T_0_ee_fun_free_mem(int mem);
extern "C" int frankino_T_0_ee_fun_checkout(void);
extern "C" void frankino_T_0_ee_fun_release(int mem);
extern "C" void frankino_T_0_ee_fun_incref(void);
extern "C" void frankino_T_0_ee_fun_decref(void);
extern "C" casadi_int frankino_T_0_ee_fun_n_in(void);
extern "C" casadi_int frankino_T_0_ee_fun_n_out(void);
extern "C" casadi_real frankino_T_0_ee_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_0_ee_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_0_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_0_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_0_ee_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_0_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_0_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_0_ee_fun_SZ_ARG 1
#define frankino_T_0_ee_fun_SZ_RES 1
#define frankino_T_0_ee_fun_SZ_IW 0
#define frankino_T_0_ee_fun_SZ_W 0
extern "C" int frankino_T_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_1_fun_alloc_mem(void);
extern "C" int frankino_T_1_fun_init_mem(int mem);
extern "C" void frankino_T_1_fun_free_mem(int mem);
extern "C" int frankino_T_1_fun_checkout(void);
extern "C" void frankino_T_1_fun_release(int mem);
extern "C" void frankino_T_1_fun_incref(void);
extern "C" void frankino_T_1_fun_decref(void);
extern "C" casadi_int frankino_T_1_fun_n_in(void);
extern "C" casadi_int frankino_T_1_fun_n_out(void);
extern "C" casadi_real frankino_T_1_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_1_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_1_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_1_fun_SZ_ARG 1
#define frankino_T_1_fun_SZ_RES 1
#define frankino_T_1_fun_SZ_IW 0
#define frankino_T_1_fun_SZ_W 0
extern "C" int frankino_T_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_2_fun_alloc_mem(void);
extern "C" int frankino_T_2_fun_init_mem(int mem);
extern "C" void frankino_T_2_fun_free_mem(int mem);
extern "C" int frankino_T_2_fun_checkout(void);
extern "C" void frankino_T_2_fun_release(int mem);
extern "C" void frankino_T_2_fun_incref(void);
extern "C" void frankino_T_2_fun_decref(void);
extern "C" casadi_int frankino_T_2_fun_n_in(void);
extern "C" casadi_int frankino_T_2_fun_n_out(void);
extern "C" casadi_real frankino_T_2_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_2_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_2_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_2_fun_SZ_ARG 1
#define frankino_T_2_fun_SZ_RES 1
#define frankino_T_2_fun_SZ_IW 0
#define frankino_T_2_fun_SZ_W 0
extern "C" int frankino_T_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_3_fun_alloc_mem(void);
extern "C" int frankino_T_3_fun_init_mem(int mem);
extern "C" void frankino_T_3_fun_free_mem(int mem);
extern "C" int frankino_T_3_fun_checkout(void);
extern "C" void frankino_T_3_fun_release(int mem);
extern "C" void frankino_T_3_fun_incref(void);
extern "C" void frankino_T_3_fun_decref(void);
extern "C" casadi_int frankino_T_3_fun_n_in(void);
extern "C" casadi_int frankino_T_3_fun_n_out(void);
extern "C" casadi_real frankino_T_3_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_3_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_3_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_3_fun_SZ_ARG 1
#define frankino_T_3_fun_SZ_RES 1
#define frankino_T_3_fun_SZ_IW 0
#define frankino_T_3_fun_SZ_W 0
extern "C" int frankino_T_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_4_fun_alloc_mem(void);
extern "C" int frankino_T_4_fun_init_mem(int mem);
extern "C" void frankino_T_4_fun_free_mem(int mem);
extern "C" int frankino_T_4_fun_checkout(void);
extern "C" void frankino_T_4_fun_release(int mem);
extern "C" void frankino_T_4_fun_incref(void);
extern "C" void frankino_T_4_fun_decref(void);
extern "C" casadi_int frankino_T_4_fun_n_in(void);
extern "C" casadi_int frankino_T_4_fun_n_out(void);
extern "C" casadi_real frankino_T_4_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_4_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_4_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_4_fun_SZ_ARG 1
#define frankino_T_4_fun_SZ_RES 1
#define frankino_T_4_fun_SZ_IW 0
#define frankino_T_4_fun_SZ_W 0
extern "C" int frankino_T_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_5_fun_alloc_mem(void);
extern "C" int frankino_T_5_fun_init_mem(int mem);
extern "C" void frankino_T_5_fun_free_mem(int mem);
extern "C" int frankino_T_5_fun_checkout(void);
extern "C" void frankino_T_5_fun_release(int mem);
extern "C" void frankino_T_5_fun_incref(void);
extern "C" void frankino_T_5_fun_decref(void);
extern "C" casadi_int frankino_T_5_fun_n_in(void);
extern "C" casadi_int frankino_T_5_fun_n_out(void);
extern "C" casadi_real frankino_T_5_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_5_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_5_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_5_fun_SZ_ARG 1
#define frankino_T_5_fun_SZ_RES 1
#define frankino_T_5_fun_SZ_IW 0
#define frankino_T_5_fun_SZ_W 0
extern "C" int frankino_T_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_6_fun_alloc_mem(void);
extern "C" int frankino_T_6_fun_init_mem(int mem);
extern "C" void frankino_T_6_fun_free_mem(int mem);
extern "C" int frankino_T_6_fun_checkout(void);
extern "C" void frankino_T_6_fun_release(int mem);
extern "C" void frankino_T_6_fun_incref(void);
extern "C" void frankino_T_6_fun_decref(void);
extern "C" casadi_int frankino_T_6_fun_n_in(void);
extern "C" casadi_int frankino_T_6_fun_n_out(void);
extern "C" casadi_real frankino_T_6_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_6_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_6_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_6_fun_SZ_ARG 1
#define frankino_T_6_fun_SZ_RES 1
#define frankino_T_6_fun_SZ_IW 0
#define frankino_T_6_fun_SZ_W 0
extern "C" int frankino_T_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_T_7_fun_alloc_mem(void);
extern "C" int frankino_T_7_fun_init_mem(int mem);
extern "C" void frankino_T_7_fun_free_mem(int mem);
extern "C" int frankino_T_7_fun_checkout(void);
extern "C" void frankino_T_7_fun_release(int mem);
extern "C" void frankino_T_7_fun_incref(void);
extern "C" void frankino_T_7_fun_decref(void);
extern "C" casadi_int frankino_T_7_fun_n_in(void);
extern "C" casadi_int frankino_T_7_fun_n_out(void);
extern "C" casadi_real frankino_T_7_fun_default_in(casadi_int i);
extern "C" const char* frankino_T_7_fun_name_in(casadi_int i);
extern "C" const char* frankino_T_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_T_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_T_7_fun_sparsity_out(casadi_int i);
extern "C" int frankino_T_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_T_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_T_7_fun_SZ_ARG 1
#define frankino_T_7_fun_SZ_RES 1
#define frankino_T_7_fun_SZ_IW 0
#define frankino_T_7_fun_SZ_W 0
extern "C" int frankino_Yr_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_Yr_fun_alloc_mem(void);
extern "C" int frankino_Yr_fun_init_mem(int mem);
extern "C" void frankino_Yr_fun_free_mem(int mem);
extern "C" int frankino_Yr_fun_checkout(void);
extern "C" void frankino_Yr_fun_release(int mem);
extern "C" void frankino_Yr_fun_incref(void);
extern "C" void frankino_Yr_fun_decref(void);
extern "C" casadi_int frankino_Yr_fun_n_in(void);
extern "C" casadi_int frankino_Yr_fun_n_out(void);
extern "C" casadi_real frankino_Yr_fun_default_in(casadi_int i);
extern "C" const char* frankino_Yr_fun_name_in(casadi_int i);
extern "C" const char* frankino_Yr_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_Yr_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_Yr_fun_sparsity_out(casadi_int i);
extern "C" int frankino_Yr_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_Yr_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_Yr_fun_SZ_ARG 4
#define frankino_Yr_fun_SZ_RES 1
#define frankino_Yr_fun_SZ_IW 0
#define frankino_Yr_fun_SZ_W 0
extern "C" int frankino_reg_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_reg_C_fun_alloc_mem(void);
extern "C" int frankino_reg_C_fun_init_mem(int mem);
extern "C" void frankino_reg_C_fun_free_mem(int mem);
extern "C" int frankino_reg_C_fun_checkout(void);
extern "C" void frankino_reg_C_fun_release(int mem);
extern "C" void frankino_reg_C_fun_incref(void);
extern "C" void frankino_reg_C_fun_decref(void);
extern "C" casadi_int frankino_reg_C_fun_n_in(void);
extern "C" casadi_int frankino_reg_C_fun_n_out(void);
extern "C" casadi_real frankino_reg_C_fun_default_in(casadi_int i);
extern "C" const char* frankino_reg_C_fun_name_in(casadi_int i);
extern "C" const char* frankino_reg_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_reg_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_reg_C_fun_sparsity_out(casadi_int i);
extern "C" int frankino_reg_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_reg_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_reg_C_fun_SZ_ARG 3
#define frankino_reg_C_fun_SZ_RES 1
#define frankino_reg_C_fun_SZ_IW 0
#define frankino_reg_C_fun_SZ_W 0
extern "C" int frankino_reg_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_reg_G_fun_alloc_mem(void);
extern "C" int frankino_reg_G_fun_init_mem(int mem);
extern "C" void frankino_reg_G_fun_free_mem(int mem);
extern "C" int frankino_reg_G_fun_checkout(void);
extern "C" void frankino_reg_G_fun_release(int mem);
extern "C" void frankino_reg_G_fun_incref(void);
extern "C" void frankino_reg_G_fun_decref(void);
extern "C" casadi_int frankino_reg_G_fun_n_in(void);
extern "C" casadi_int frankino_reg_G_fun_n_out(void);
extern "C" casadi_real frankino_reg_G_fun_default_in(casadi_int i);
extern "C" const char* frankino_reg_G_fun_name_in(casadi_int i);
extern "C" const char* frankino_reg_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_reg_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_reg_G_fun_sparsity_out(casadi_int i);
extern "C" int frankino_reg_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_reg_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_reg_G_fun_SZ_ARG 1
#define frankino_reg_G_fun_SZ_RES 1
#define frankino_reg_G_fun_SZ_IW 0
#define frankino_reg_G_fun_SZ_W 0
extern "C" int frankino_reg_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int frankino_reg_M_fun_alloc_mem(void);
extern "C" int frankino_reg_M_fun_init_mem(int mem);
extern "C" void frankino_reg_M_fun_free_mem(int mem);
extern "C" int frankino_reg_M_fun_checkout(void);
extern "C" void frankino_reg_M_fun_release(int mem);
extern "C" void frankino_reg_M_fun_incref(void);
extern "C" void frankino_reg_M_fun_decref(void);
extern "C" casadi_int frankino_reg_M_fun_n_in(void);
extern "C" casadi_int frankino_reg_M_fun_n_out(void);
extern "C" casadi_real frankino_reg_M_fun_default_in(casadi_int i);
extern "C" const char* frankino_reg_M_fun_name_in(casadi_int i);
extern "C" const char* frankino_reg_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* frankino_reg_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* frankino_reg_M_fun_sparsity_out(casadi_int i);
extern "C" int frankino_reg_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int frankino_reg_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define frankino_reg_M_fun_SZ_ARG 2
#define frankino_reg_M_fun_SZ_RES 1
#define frankino_reg_M_fun_SZ_IW 0
#define frankino_reg_M_fun_SZ_W 0
