computed_torque_controller:
    type: panda_controllers/ComputedTorque
    arm_id: panda
    joint_names:
         - panda_joint1
         - panda_joint2
         - panda_joint3
         - panda_joint4
         - panda_joint5
         - panda_joint6
         - panda_joint7
    # --- Controller parameters --- #
    kp1: 300.0   #default: 120.0
    kp2: 150.0   #default: 70.0
    kp3: 30.0    #default: 50.0
    kp4: 0.0
    kv1: 30.0
    kv2: 15.0
    kv3: 3.0
    kv4: 0.0
    wrist_stiffness: 0.4
    wrist_offset: 0.0
    wrist_theta: 0.0
    wrist_fixed: false
    dt: 5
