joint_names_arr: &jointNames
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

cartesian_impedance_controller_softbots:
    type: panda_controllers/CartesianImpedanceControllerSoftbots
    arm_id: panda
    joint_names: *jointNames

computed_torque_controller:
    type: panda_controllers/ComputedTorque
    arm_id: panda
    joint_names: *jointNames
    
    # --- Controller parameters --- #
    kp1: 300.0   #default: 120.0
    kp2: 150.0   #default: 70.0
    kp3: 30.0    #default: 50.0
    kv1: 30.0
    kv2: 15.0
    kv3: 3.0
    dt: 0.001
    gainRlinks: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]                   # gain for R matrix
    gainRparam: [1, 0.1, 0.01]                          # gain proportional to [mass, mass*length, mass*length^2] 
    update_param: false
    P11: [0.5349, 0.0667, 0.0667, 0.0667, 0.0836, 0.0836, 0.2222]
    P22: [0.4703, 5.0167, 5.0167, 5.0167, 5.0333, 5.0333, 5.1667]
    Pout: [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5]

backstepping_controller:
    type: panda_controllers/Backstepping
    arm_id: panda
    joint_names: *jointNames
    
    # --- Controller parameters --- #
    gainLambda: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]       # gain for Lambda matrix
    gainRlinks: [0, 0, 0, 0, 0, 0, 1]     # gain for R matrix
    gainRparam: [1, 0.1, 0.01]                          # gain proportional to [mass, mass*length, mass*length^2] 
    gainKd: [40, 40, 40, 40, 20, 20, 4]                   # gain for Kd matrix
    update_param: false                                 # bool to update inertial parameters
    
