# Trajectory parameters for command_node

duration: &time 60

liss_default: &liss_default
  ampX: 0.10
  ampY: 0.15
  ampZ: 0.10
  freqX: 0.6
  freqY: 0.3 # must be different from 0
  freqZ: 0.2
  phiX : 0
  phiZ : 0
  offX : 0.0
  offY : 0.0
  offZ : 0.0
  duration: *time

liss: &liss
  <<: *liss_default  # Copia tutti i valori da liss1 usando l'anchor
  ampZ: 0.1
  freqZ: 0.4

minjerk:
  xf: 0.311613
  yf: 0.40
  zf: 0.588755
  duration: 5

lissajous: *liss

flag:
  type: 1 # 1: lissajous, 2: minjerk, 3: script
