/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int franka_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_fun_alloc_mem(void);
extern "C" int franka_C_fun_init_mem(int mem);
extern "C" void franka_C_fun_free_mem(int mem);
extern "C" int franka_C_fun_checkout(void);
extern "C" void franka_C_fun_release(int mem);
extern "C" void franka_C_fun_incref(void);
extern "C" void franka_C_fun_decref(void);
extern "C" casadi_int franka_C_fun_n_in(void);
extern "C" casadi_int franka_C_fun_n_out(void);
extern "C" casadi_real franka_C_fun_default_in(casadi_int i);
extern "C" const char* franka_C_fun_name_in(casadi_int i);
extern "C" const char* franka_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_fun_SZ_ARG 3
#define franka_C_fun_SZ_RES 1
#define franka_C_fun_SZ_IW 0
#define franka_C_fun_SZ_W 1343
extern "C" int franka_C_std_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_std_fun_alloc_mem(void);
extern "C" int franka_C_std_fun_init_mem(int mem);
extern "C" void franka_C_std_fun_free_mem(int mem);
extern "C" int franka_C_std_fun_checkout(void);
extern "C" void franka_C_std_fun_release(int mem);
extern "C" void franka_C_std_fun_incref(void);
extern "C" void franka_C_std_fun_decref(void);
extern "C" casadi_int franka_C_std_fun_n_in(void);
extern "C" casadi_int franka_C_std_fun_n_out(void);
extern "C" casadi_real franka_C_std_fun_default_in(casadi_int i);
extern "C" const char* franka_C_std_fun_name_in(casadi_int i);
extern "C" const char* franka_C_std_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_std_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_std_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_std_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_std_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_std_fun_SZ_ARG 3
#define franka_C_std_fun_SZ_RES 1
#define franka_C_std_fun_SZ_IW 0
#define franka_C_std_fun_SZ_W 484
extern "C" int franka_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_G_fun_alloc_mem(void);
extern "C" int franka_G_fun_init_mem(int mem);
extern "C" void franka_G_fun_free_mem(int mem);
extern "C" int franka_G_fun_checkout(void);
extern "C" void franka_G_fun_release(int mem);
extern "C" void franka_G_fun_incref(void);
extern "C" void franka_G_fun_decref(void);
extern "C" casadi_int franka_G_fun_n_in(void);
extern "C" casadi_int franka_G_fun_n_out(void);
extern "C" casadi_real franka_G_fun_default_in(casadi_int i);
extern "C" const char* franka_G_fun_name_in(casadi_int i);
extern "C" const char* franka_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_G_fun_sparsity_out(casadi_int i);
extern "C" int franka_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_G_fun_SZ_ARG 2
#define franka_G_fun_SZ_RES 1
#define franka_G_fun_SZ_IW 0
#define franka_G_fun_SZ_W 56
extern "C" int franka_J_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_1_fun_alloc_mem(void);
extern "C" int franka_J_1_fun_init_mem(int mem);
extern "C" void franka_J_1_fun_free_mem(int mem);
extern "C" int franka_J_1_fun_checkout(void);
extern "C" void franka_J_1_fun_release(int mem);
extern "C" void franka_J_1_fun_incref(void);
extern "C" void franka_J_1_fun_decref(void);
extern "C" casadi_int franka_J_1_fun_n_in(void);
extern "C" casadi_int franka_J_1_fun_n_out(void);
extern "C" casadi_real franka_J_1_fun_default_in(casadi_int i);
extern "C" const char* franka_J_1_fun_name_in(casadi_int i);
extern "C" const char* franka_J_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_1_fun_SZ_ARG 1
#define franka_J_1_fun_SZ_RES 1
#define franka_J_1_fun_SZ_IW 0
#define franka_J_1_fun_SZ_W 2
extern "C" int franka_J_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_2_fun_alloc_mem(void);
extern "C" int franka_J_2_fun_init_mem(int mem);
extern "C" void franka_J_2_fun_free_mem(int mem);
extern "C" int franka_J_2_fun_checkout(void);
extern "C" void franka_J_2_fun_release(int mem);
extern "C" void franka_J_2_fun_incref(void);
extern "C" void franka_J_2_fun_decref(void);
extern "C" casadi_int franka_J_2_fun_n_in(void);
extern "C" casadi_int franka_J_2_fun_n_out(void);
extern "C" casadi_real franka_J_2_fun_default_in(casadi_int i);
extern "C" const char* franka_J_2_fun_name_in(casadi_int i);
extern "C" const char* franka_J_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_2_fun_SZ_ARG 1
#define franka_J_2_fun_SZ_RES 1
#define franka_J_2_fun_SZ_IW 0
#define franka_J_2_fun_SZ_W 3
extern "C" int franka_J_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_3_fun_alloc_mem(void);
extern "C" int franka_J_3_fun_init_mem(int mem);
extern "C" void franka_J_3_fun_free_mem(int mem);
extern "C" int franka_J_3_fun_checkout(void);
extern "C" void franka_J_3_fun_release(int mem);
extern "C" void franka_J_3_fun_incref(void);
extern "C" void franka_J_3_fun_decref(void);
extern "C" casadi_int franka_J_3_fun_n_in(void);
extern "C" casadi_int franka_J_3_fun_n_out(void);
extern "C" casadi_real franka_J_3_fun_default_in(casadi_int i);
extern "C" const char* franka_J_3_fun_name_in(casadi_int i);
extern "C" const char* franka_J_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_3_fun_SZ_ARG 1
#define franka_J_3_fun_SZ_RES 1
#define franka_J_3_fun_SZ_IW 0
#define franka_J_3_fun_SZ_W 12
extern "C" int franka_J_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_4_fun_alloc_mem(void);
extern "C" int franka_J_4_fun_init_mem(int mem);
extern "C" void franka_J_4_fun_free_mem(int mem);
extern "C" int franka_J_4_fun_checkout(void);
extern "C" void franka_J_4_fun_release(int mem);
extern "C" void franka_J_4_fun_incref(void);
extern "C" void franka_J_4_fun_decref(void);
extern "C" casadi_int franka_J_4_fun_n_in(void);
extern "C" casadi_int franka_J_4_fun_n_out(void);
extern "C" casadi_real franka_J_4_fun_default_in(casadi_int i);
extern "C" const char* franka_J_4_fun_name_in(casadi_int i);
extern "C" const char* franka_J_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_4_fun_SZ_ARG 1
#define franka_J_4_fun_SZ_RES 1
#define franka_J_4_fun_SZ_IW 0
#define franka_J_4_fun_SZ_W 21
extern "C" int franka_J_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_5_fun_alloc_mem(void);
extern "C" int franka_J_5_fun_init_mem(int mem);
extern "C" void franka_J_5_fun_free_mem(int mem);
extern "C" int franka_J_5_fun_checkout(void);
extern "C" void franka_J_5_fun_release(int mem);
extern "C" void franka_J_5_fun_incref(void);
extern "C" void franka_J_5_fun_decref(void);
extern "C" casadi_int franka_J_5_fun_n_in(void);
extern "C" casadi_int franka_J_5_fun_n_out(void);
extern "C" casadi_real franka_J_5_fun_default_in(casadi_int i);
extern "C" const char* franka_J_5_fun_name_in(casadi_int i);
extern "C" const char* franka_J_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_5_fun_SZ_ARG 1
#define franka_J_5_fun_SZ_RES 1
#define franka_J_5_fun_SZ_IW 0
#define franka_J_5_fun_SZ_W 37
extern "C" int franka_J_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_6_fun_alloc_mem(void);
extern "C" int franka_J_6_fun_init_mem(int mem);
extern "C" void franka_J_6_fun_free_mem(int mem);
extern "C" int franka_J_6_fun_checkout(void);
extern "C" void franka_J_6_fun_release(int mem);
extern "C" void franka_J_6_fun_incref(void);
extern "C" void franka_J_6_fun_decref(void);
extern "C" casadi_int franka_J_6_fun_n_in(void);
extern "C" casadi_int franka_J_6_fun_n_out(void);
extern "C" casadi_real franka_J_6_fun_default_in(casadi_int i);
extern "C" const char* franka_J_6_fun_name_in(casadi_int i);
extern "C" const char* franka_J_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_6_fun_SZ_ARG 1
#define franka_J_6_fun_SZ_RES 1
#define franka_J_6_fun_SZ_IW 0
#define franka_J_6_fun_SZ_W 39
extern "C" int franka_J_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_7_fun_alloc_mem(void);
extern "C" int franka_J_7_fun_init_mem(int mem);
extern "C" void franka_J_7_fun_free_mem(int mem);
extern "C" int franka_J_7_fun_checkout(void);
extern "C" void franka_J_7_fun_release(int mem);
extern "C" void franka_J_7_fun_incref(void);
extern "C" void franka_J_7_fun_decref(void);
extern "C" casadi_int franka_J_7_fun_n_in(void);
extern "C" casadi_int franka_J_7_fun_n_out(void);
extern "C" casadi_real franka_J_7_fun_default_in(casadi_int i);
extern "C" const char* franka_J_7_fun_name_in(casadi_int i);
extern "C" const char* franka_J_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_7_fun_SZ_ARG 1
#define franka_J_7_fun_SZ_RES 1
#define franka_J_7_fun_SZ_IW 0
#define franka_J_7_fun_SZ_W 58
extern "C" int franka_J_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_8_fun_alloc_mem(void);
extern "C" int franka_J_8_fun_init_mem(int mem);
extern "C" void franka_J_8_fun_free_mem(int mem);
extern "C" int franka_J_8_fun_checkout(void);
extern "C" void franka_J_8_fun_release(int mem);
extern "C" void franka_J_8_fun_incref(void);
extern "C" void franka_J_8_fun_decref(void);
extern "C" casadi_int franka_J_8_fun_n_in(void);
extern "C" casadi_int franka_J_8_fun_n_out(void);
extern "C" casadi_real franka_J_8_fun_default_in(casadi_int i);
extern "C" const char* franka_J_8_fun_name_in(casadi_int i);
extern "C" const char* franka_J_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_8_fun_SZ_ARG 2
#define franka_J_8_fun_SZ_RES 1
#define franka_J_8_fun_SZ_IW 0
#define franka_J_8_fun_SZ_W 68
extern "C" int franka_J_cm_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_1_fun_alloc_mem(void);
extern "C" int franka_J_cm_1_fun_init_mem(int mem);
extern "C" void franka_J_cm_1_fun_free_mem(int mem);
extern "C" int franka_J_cm_1_fun_checkout(void);
extern "C" void franka_J_cm_1_fun_release(int mem);
extern "C" void franka_J_cm_1_fun_incref(void);
extern "C" void franka_J_cm_1_fun_decref(void);
extern "C" casadi_int franka_J_cm_1_fun_n_in(void);
extern "C" casadi_int franka_J_cm_1_fun_n_out(void);
extern "C" casadi_real franka_J_cm_1_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_1_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_1_fun_SZ_ARG 2
#define franka_J_cm_1_fun_SZ_RES 1
#define franka_J_cm_1_fun_SZ_IW 0
#define franka_J_cm_1_fun_SZ_W 5
extern "C" int franka_J_cm_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_2_fun_alloc_mem(void);
extern "C" int franka_J_cm_2_fun_init_mem(int mem);
extern "C" void franka_J_cm_2_fun_free_mem(int mem);
extern "C" int franka_J_cm_2_fun_checkout(void);
extern "C" void franka_J_cm_2_fun_release(int mem);
extern "C" void franka_J_cm_2_fun_incref(void);
extern "C" void franka_J_cm_2_fun_decref(void);
extern "C" casadi_int franka_J_cm_2_fun_n_in(void);
extern "C" casadi_int franka_J_cm_2_fun_n_out(void);
extern "C" casadi_real franka_J_cm_2_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_2_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_2_fun_SZ_ARG 2
#define franka_J_cm_2_fun_SZ_RES 1
#define franka_J_cm_2_fun_SZ_IW 0
#define franka_J_cm_2_fun_SZ_W 14
extern "C" int franka_J_cm_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_3_fun_alloc_mem(void);
extern "C" int franka_J_cm_3_fun_init_mem(int mem);
extern "C" void franka_J_cm_3_fun_free_mem(int mem);
extern "C" int franka_J_cm_3_fun_checkout(void);
extern "C" void franka_J_cm_3_fun_release(int mem);
extern "C" void franka_J_cm_3_fun_incref(void);
extern "C" void franka_J_cm_3_fun_decref(void);
extern "C" casadi_int franka_J_cm_3_fun_n_in(void);
extern "C" casadi_int franka_J_cm_3_fun_n_out(void);
extern "C" casadi_real franka_J_cm_3_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_3_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_3_fun_SZ_ARG 2
#define franka_J_cm_3_fun_SZ_RES 1
#define franka_J_cm_3_fun_SZ_IW 0
#define franka_J_cm_3_fun_SZ_W 24
extern "C" int franka_J_cm_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_4_fun_alloc_mem(void);
extern "C" int franka_J_cm_4_fun_init_mem(int mem);
extern "C" void franka_J_cm_4_fun_free_mem(int mem);
extern "C" int franka_J_cm_4_fun_checkout(void);
extern "C" void franka_J_cm_4_fun_release(int mem);
extern "C" void franka_J_cm_4_fun_incref(void);
extern "C" void franka_J_cm_4_fun_decref(void);
extern "C" casadi_int franka_J_cm_4_fun_n_in(void);
extern "C" casadi_int franka_J_cm_4_fun_n_out(void);
extern "C" casadi_real franka_J_cm_4_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_4_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_4_fun_SZ_ARG 2
#define franka_J_cm_4_fun_SZ_RES 1
#define franka_J_cm_4_fun_SZ_IW 0
#define franka_J_cm_4_fun_SZ_W 35
extern "C" int franka_J_cm_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_5_fun_alloc_mem(void);
extern "C" int franka_J_cm_5_fun_init_mem(int mem);
extern "C" void franka_J_cm_5_fun_free_mem(int mem);
extern "C" int franka_J_cm_5_fun_checkout(void);
extern "C" void franka_J_cm_5_fun_release(int mem);
extern "C" void franka_J_cm_5_fun_incref(void);
extern "C" void franka_J_cm_5_fun_decref(void);
extern "C" casadi_int franka_J_cm_5_fun_n_in(void);
extern "C" casadi_int franka_J_cm_5_fun_n_out(void);
extern "C" casadi_real franka_J_cm_5_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_5_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_5_fun_SZ_ARG 2
#define franka_J_cm_5_fun_SZ_RES 1
#define franka_J_cm_5_fun_SZ_IW 0
#define franka_J_cm_5_fun_SZ_W 48
extern "C" int franka_J_cm_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_6_fun_alloc_mem(void);
extern "C" int franka_J_cm_6_fun_init_mem(int mem);
extern "C" void franka_J_cm_6_fun_free_mem(int mem);
extern "C" int franka_J_cm_6_fun_checkout(void);
extern "C" void franka_J_cm_6_fun_release(int mem);
extern "C" void franka_J_cm_6_fun_incref(void);
extern "C" void franka_J_cm_6_fun_decref(void);
extern "C" casadi_int franka_J_cm_6_fun_n_in(void);
extern "C" casadi_int franka_J_cm_6_fun_n_out(void);
extern "C" casadi_real franka_J_cm_6_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_6_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_6_fun_SZ_ARG 2
#define franka_J_cm_6_fun_SZ_RES 1
#define franka_J_cm_6_fun_SZ_IW 0
#define franka_J_cm_6_fun_SZ_W 55
extern "C" int franka_J_cm_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_7_fun_alloc_mem(void);
extern "C" int franka_J_cm_7_fun_init_mem(int mem);
extern "C" void franka_J_cm_7_fun_free_mem(int mem);
extern "C" int franka_J_cm_7_fun_checkout(void);
extern "C" void franka_J_cm_7_fun_release(int mem);
extern "C" void franka_J_cm_7_fun_incref(void);
extern "C" void franka_J_cm_7_fun_decref(void);
extern "C" casadi_int franka_J_cm_7_fun_n_in(void);
extern "C" casadi_int franka_J_cm_7_fun_n_out(void);
extern "C" casadi_real franka_J_cm_7_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_7_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_7_fun_SZ_ARG 2
#define franka_J_cm_7_fun_SZ_RES 1
#define franka_J_cm_7_fun_SZ_IW 0
#define franka_J_cm_7_fun_SZ_W 69
extern "C" int franka_J_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_ee_fun_alloc_mem(void);
extern "C" int franka_J_ee_fun_init_mem(int mem);
extern "C" void franka_J_ee_fun_free_mem(int mem);
extern "C" int franka_J_ee_fun_checkout(void);
extern "C" void franka_J_ee_fun_release(int mem);
extern "C" void franka_J_ee_fun_incref(void);
extern "C" void franka_J_ee_fun_decref(void);
extern "C" casadi_int franka_J_ee_fun_n_in(void);
extern "C" casadi_int franka_J_ee_fun_n_out(void);
extern "C" casadi_real franka_J_ee_fun_default_in(casadi_int i);
extern "C" const char* franka_J_ee_fun_name_in(casadi_int i);
extern "C" const char* franka_J_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_ee_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_ee_fun_SZ_ARG 2
#define franka_J_ee_fun_SZ_RES 1
#define franka_J_ee_fun_SZ_IW 0
#define franka_J_ee_fun_SZ_W 68
extern "C" int franka_J_ee_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_ee_dot_fun_alloc_mem(void);
extern "C" int franka_J_ee_dot_fun_init_mem(int mem);
extern "C" void franka_J_ee_dot_fun_free_mem(int mem);
extern "C" int franka_J_ee_dot_fun_checkout(void);
extern "C" void franka_J_ee_dot_fun_release(int mem);
extern "C" void franka_J_ee_dot_fun_incref(void);
extern "C" void franka_J_ee_dot_fun_decref(void);
extern "C" casadi_int franka_J_ee_dot_fun_n_in(void);
extern "C" casadi_int franka_J_ee_dot_fun_n_out(void);
extern "C" casadi_real franka_J_ee_dot_fun_default_in(casadi_int i);
extern "C" const char* franka_J_ee_dot_fun_name_in(casadi_int i);
extern "C" const char* franka_J_ee_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_ee_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_ee_dot_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_ee_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_ee_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_ee_dot_fun_SZ_ARG 3
#define franka_J_ee_dot_fun_SZ_RES 1
#define franka_J_ee_dot_fun_SZ_IW 0
#define franka_J_ee_dot_fun_SZ_W 137
extern "C" int franka_J_ee_pinv_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_ee_pinv_fun_alloc_mem(void);
extern "C" int franka_J_ee_pinv_fun_init_mem(int mem);
extern "C" void franka_J_ee_pinv_fun_free_mem(int mem);
extern "C" int franka_J_ee_pinv_fun_checkout(void);
extern "C" void franka_J_ee_pinv_fun_release(int mem);
extern "C" void franka_J_ee_pinv_fun_incref(void);
extern "C" void franka_J_ee_pinv_fun_decref(void);
extern "C" casadi_int franka_J_ee_pinv_fun_n_in(void);
extern "C" casadi_int franka_J_ee_pinv_fun_n_out(void);
extern "C" casadi_real franka_J_ee_pinv_fun_default_in(casadi_int i);
extern "C" const char* franka_J_ee_pinv_fun_name_in(casadi_int i);
extern "C" const char* franka_J_ee_pinv_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_ee_pinv_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_ee_pinv_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_ee_pinv_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_ee_pinv_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_ee_pinv_fun_SZ_ARG 2
#define franka_J_ee_pinv_fun_SZ_RES 1
#define franka_J_ee_pinv_fun_SZ_IW 0
#define franka_J_ee_pinv_fun_SZ_W 98
extern "C" int franka_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_M_fun_alloc_mem(void);
extern "C" int franka_M_fun_init_mem(int mem);
extern "C" void franka_M_fun_free_mem(int mem);
extern "C" int franka_M_fun_checkout(void);
extern "C" void franka_M_fun_release(int mem);
extern "C" void franka_M_fun_incref(void);
extern "C" void franka_M_fun_decref(void);
extern "C" casadi_int franka_M_fun_n_in(void);
extern "C" casadi_int franka_M_fun_n_out(void);
extern "C" casadi_real franka_M_fun_default_in(casadi_int i);
extern "C" const char* franka_M_fun_name_in(casadi_int i);
extern "C" const char* franka_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_M_fun_sparsity_out(casadi_int i);
extern "C" int franka_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_M_fun_SZ_ARG 2
#define franka_M_fun_SZ_RES 1
#define franka_M_fun_SZ_IW 0
#define franka_M_fun_SZ_W 247
extern "C" int franka_T_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_fun_alloc_mem(void);
extern "C" int franka_T_0_fun_init_mem(int mem);
extern "C" void franka_T_0_fun_free_mem(int mem);
extern "C" int franka_T_0_fun_checkout(void);
extern "C" void franka_T_0_fun_release(int mem);
extern "C" void franka_T_0_fun_incref(void);
extern "C" void franka_T_0_fun_decref(void);
extern "C" casadi_int franka_T_0_fun_n_in(void);
extern "C" casadi_int franka_T_0_fun_n_out(void);
extern "C" casadi_real franka_T_0_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_fun_SZ_ARG 0
#define franka_T_0_fun_SZ_RES 1
#define franka_T_0_fun_SZ_IW 0
#define franka_T_0_fun_SZ_W 2
extern "C" int franka_T_0_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_0_fun_alloc_mem(void);
extern "C" int franka_T_0_0_fun_init_mem(int mem);
extern "C" void franka_T_0_0_fun_free_mem(int mem);
extern "C" int franka_T_0_0_fun_checkout(void);
extern "C" void franka_T_0_0_fun_release(int mem);
extern "C" void franka_T_0_0_fun_incref(void);
extern "C" void franka_T_0_0_fun_decref(void);
extern "C" casadi_int franka_T_0_0_fun_n_in(void);
extern "C" casadi_int franka_T_0_0_fun_n_out(void);
extern "C" casadi_real franka_T_0_0_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_0_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_0_fun_SZ_ARG 0
#define franka_T_0_0_fun_SZ_RES 1
#define franka_T_0_0_fun_SZ_IW 0
#define franka_T_0_0_fun_SZ_W 2
extern "C" int franka_T_0_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_1_fun_alloc_mem(void);
extern "C" int franka_T_0_1_fun_init_mem(int mem);
extern "C" void franka_T_0_1_fun_free_mem(int mem);
extern "C" int franka_T_0_1_fun_checkout(void);
extern "C" void franka_T_0_1_fun_release(int mem);
extern "C" void franka_T_0_1_fun_incref(void);
extern "C" void franka_T_0_1_fun_decref(void);
extern "C" casadi_int franka_T_0_1_fun_n_in(void);
extern "C" casadi_int franka_T_0_1_fun_n_out(void);
extern "C" casadi_real franka_T_0_1_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_1_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_1_fun_SZ_ARG 1
#define franka_T_0_1_fun_SZ_RES 1
#define franka_T_0_1_fun_SZ_IW 0
#define franka_T_0_1_fun_SZ_W 3
extern "C" int franka_T_0_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_2_fun_alloc_mem(void);
extern "C" int franka_T_0_2_fun_init_mem(int mem);
extern "C" void franka_T_0_2_fun_free_mem(int mem);
extern "C" int franka_T_0_2_fun_checkout(void);
extern "C" void franka_T_0_2_fun_release(int mem);
extern "C" void franka_T_0_2_fun_incref(void);
extern "C" void franka_T_0_2_fun_decref(void);
extern "C" casadi_int franka_T_0_2_fun_n_in(void);
extern "C" casadi_int franka_T_0_2_fun_n_out(void);
extern "C" casadi_real franka_T_0_2_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_2_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_2_fun_SZ_ARG 1
#define franka_T_0_2_fun_SZ_RES 1
#define franka_T_0_2_fun_SZ_IW 0
#define franka_T_0_2_fun_SZ_W 10
extern "C" int franka_T_0_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_3_fun_alloc_mem(void);
extern "C" int franka_T_0_3_fun_init_mem(int mem);
extern "C" void franka_T_0_3_fun_free_mem(int mem);
extern "C" int franka_T_0_3_fun_checkout(void);
extern "C" void franka_T_0_3_fun_release(int mem);
extern "C" void franka_T_0_3_fun_incref(void);
extern "C" void franka_T_0_3_fun_decref(void);
extern "C" casadi_int franka_T_0_3_fun_n_in(void);
extern "C" casadi_int franka_T_0_3_fun_n_out(void);
extern "C" casadi_real franka_T_0_3_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_3_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_3_fun_SZ_ARG 1
#define franka_T_0_3_fun_SZ_RES 1
#define franka_T_0_3_fun_SZ_IW 0
#define franka_T_0_3_fun_SZ_W 17
extern "C" int franka_T_0_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_4_fun_alloc_mem(void);
extern "C" int franka_T_0_4_fun_init_mem(int mem);
extern "C" void franka_T_0_4_fun_free_mem(int mem);
extern "C" int franka_T_0_4_fun_checkout(void);
extern "C" void franka_T_0_4_fun_release(int mem);
extern "C" void franka_T_0_4_fun_incref(void);
extern "C" void franka_T_0_4_fun_decref(void);
extern "C" casadi_int franka_T_0_4_fun_n_in(void);
extern "C" casadi_int franka_T_0_4_fun_n_out(void);
extern "C" casadi_real franka_T_0_4_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_4_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_4_fun_SZ_ARG 1
#define franka_T_0_4_fun_SZ_RES 1
#define franka_T_0_4_fun_SZ_IW 0
#define franka_T_0_4_fun_SZ_W 25
extern "C" int franka_T_0_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_5_fun_alloc_mem(void);
extern "C" int franka_T_0_5_fun_init_mem(int mem);
extern "C" void franka_T_0_5_fun_free_mem(int mem);
extern "C" int franka_T_0_5_fun_checkout(void);
extern "C" void franka_T_0_5_fun_release(int mem);
extern "C" void franka_T_0_5_fun_incref(void);
extern "C" void franka_T_0_5_fun_decref(void);
extern "C" casadi_int franka_T_0_5_fun_n_in(void);
extern "C" casadi_int franka_T_0_5_fun_n_out(void);
extern "C" casadi_real franka_T_0_5_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_5_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_5_fun_SZ_ARG 1
#define franka_T_0_5_fun_SZ_RES 1
#define franka_T_0_5_fun_SZ_IW 0
#define franka_T_0_5_fun_SZ_W 34
extern "C" int franka_T_0_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_6_fun_alloc_mem(void);
extern "C" int franka_T_0_6_fun_init_mem(int mem);
extern "C" void franka_T_0_6_fun_free_mem(int mem);
extern "C" int franka_T_0_6_fun_checkout(void);
extern "C" void franka_T_0_6_fun_release(int mem);
extern "C" void franka_T_0_6_fun_incref(void);
extern "C" void franka_T_0_6_fun_decref(void);
extern "C" casadi_int franka_T_0_6_fun_n_in(void);
extern "C" casadi_int franka_T_0_6_fun_n_out(void);
extern "C" casadi_real franka_T_0_6_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_6_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_6_fun_SZ_ARG 1
#define franka_T_0_6_fun_SZ_RES 1
#define franka_T_0_6_fun_SZ_IW 0
#define franka_T_0_6_fun_SZ_W 45
extern "C" int franka_T_0_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_7_fun_alloc_mem(void);
extern "C" int franka_T_0_7_fun_init_mem(int mem);
extern "C" void franka_T_0_7_fun_free_mem(int mem);
extern "C" int franka_T_0_7_fun_checkout(void);
extern "C" void franka_T_0_7_fun_release(int mem);
extern "C" void franka_T_0_7_fun_incref(void);
extern "C" void franka_T_0_7_fun_decref(void);
extern "C" casadi_int franka_T_0_7_fun_n_in(void);
extern "C" casadi_int franka_T_0_7_fun_n_out(void);
extern "C" casadi_real franka_T_0_7_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_7_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_7_fun_SZ_ARG 1
#define franka_T_0_7_fun_SZ_RES 1
#define franka_T_0_7_fun_SZ_IW 0
#define franka_T_0_7_fun_SZ_W 52
extern "C" int franka_T_0_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_8_fun_alloc_mem(void);
extern "C" int franka_T_0_8_fun_init_mem(int mem);
extern "C" void franka_T_0_8_fun_free_mem(int mem);
extern "C" int franka_T_0_8_fun_checkout(void);
extern "C" void franka_T_0_8_fun_release(int mem);
extern "C" void franka_T_0_8_fun_incref(void);
extern "C" void franka_T_0_8_fun_decref(void);
extern "C" casadi_int franka_T_0_8_fun_n_in(void);
extern "C" casadi_int franka_T_0_8_fun_n_out(void);
extern "C" casadi_real franka_T_0_8_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_8_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_8_fun_SZ_ARG 2
#define franka_T_0_8_fun_SZ_RES 1
#define franka_T_0_8_fun_SZ_IW 0
#define franka_T_0_8_fun_SZ_W 53
extern "C" int franka_T_0_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_ee_fun_alloc_mem(void);
extern "C" int franka_T_0_ee_fun_init_mem(int mem);
extern "C" void franka_T_0_ee_fun_free_mem(int mem);
extern "C" int franka_T_0_ee_fun_checkout(void);
extern "C" void franka_T_0_ee_fun_release(int mem);
extern "C" void franka_T_0_ee_fun_incref(void);
extern "C" void franka_T_0_ee_fun_decref(void);
extern "C" casadi_int franka_T_0_ee_fun_n_in(void);
extern "C" casadi_int franka_T_0_ee_fun_n_out(void);
extern "C" casadi_real franka_T_0_ee_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_ee_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_ee_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_ee_fun_SZ_ARG 2
#define franka_T_0_ee_fun_SZ_RES 1
#define franka_T_0_ee_fun_SZ_IW 0
#define franka_T_0_ee_fun_SZ_W 53
extern "C" int franka_T_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_1_fun_alloc_mem(void);
extern "C" int franka_T_1_fun_init_mem(int mem);
extern "C" void franka_T_1_fun_free_mem(int mem);
extern "C" int franka_T_1_fun_checkout(void);
extern "C" void franka_T_1_fun_release(int mem);
extern "C" void franka_T_1_fun_incref(void);
extern "C" void franka_T_1_fun_decref(void);
extern "C" casadi_int franka_T_1_fun_n_in(void);
extern "C" casadi_int franka_T_1_fun_n_out(void);
extern "C" casadi_real franka_T_1_fun_default_in(casadi_int i);
extern "C" const char* franka_T_1_fun_name_in(casadi_int i);
extern "C" const char* franka_T_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_1_fun_SZ_ARG 1
#define franka_T_1_fun_SZ_RES 1
#define franka_T_1_fun_SZ_IW 0
#define franka_T_1_fun_SZ_W 3
extern "C" int franka_T_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_2_fun_alloc_mem(void);
extern "C" int franka_T_2_fun_init_mem(int mem);
extern "C" void franka_T_2_fun_free_mem(int mem);
extern "C" int franka_T_2_fun_checkout(void);
extern "C" void franka_T_2_fun_release(int mem);
extern "C" void franka_T_2_fun_incref(void);
extern "C" void franka_T_2_fun_decref(void);
extern "C" casadi_int franka_T_2_fun_n_in(void);
extern "C" casadi_int franka_T_2_fun_n_out(void);
extern "C" casadi_real franka_T_2_fun_default_in(casadi_int i);
extern "C" const char* franka_T_2_fun_name_in(casadi_int i);
extern "C" const char* franka_T_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_2_fun_SZ_ARG 1
#define franka_T_2_fun_SZ_RES 1
#define franka_T_2_fun_SZ_IW 0
#define franka_T_2_fun_SZ_W 4
extern "C" int franka_T_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_3_fun_alloc_mem(void);
extern "C" int franka_T_3_fun_init_mem(int mem);
extern "C" void franka_T_3_fun_free_mem(int mem);
extern "C" int franka_T_3_fun_checkout(void);
extern "C" void franka_T_3_fun_release(int mem);
extern "C" void franka_T_3_fun_incref(void);
extern "C" void franka_T_3_fun_decref(void);
extern "C" casadi_int franka_T_3_fun_n_in(void);
extern "C" casadi_int franka_T_3_fun_n_out(void);
extern "C" casadi_real franka_T_3_fun_default_in(casadi_int i);
extern "C" const char* franka_T_3_fun_name_in(casadi_int i);
extern "C" const char* franka_T_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_3_fun_SZ_ARG 1
#define franka_T_3_fun_SZ_RES 1
#define franka_T_3_fun_SZ_IW 0
#define franka_T_3_fun_SZ_W 4
extern "C" int franka_T_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_4_fun_alloc_mem(void);
extern "C" int franka_T_4_fun_init_mem(int mem);
extern "C" void franka_T_4_fun_free_mem(int mem);
extern "C" int franka_T_4_fun_checkout(void);
extern "C" void franka_T_4_fun_release(int mem);
extern "C" void franka_T_4_fun_incref(void);
extern "C" void franka_T_4_fun_decref(void);
extern "C" casadi_int franka_T_4_fun_n_in(void);
extern "C" casadi_int franka_T_4_fun_n_out(void);
extern "C" casadi_real franka_T_4_fun_default_in(casadi_int i);
extern "C" const char* franka_T_4_fun_name_in(casadi_int i);
extern "C" const char* franka_T_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_4_fun_SZ_ARG 1
#define franka_T_4_fun_SZ_RES 1
#define franka_T_4_fun_SZ_IW 0
#define franka_T_4_fun_SZ_W 4
extern "C" int franka_T_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_5_fun_alloc_mem(void);
extern "C" int franka_T_5_fun_init_mem(int mem);
extern "C" void franka_T_5_fun_free_mem(int mem);
extern "C" int franka_T_5_fun_checkout(void);
extern "C" void franka_T_5_fun_release(int mem);
extern "C" void franka_T_5_fun_incref(void);
extern "C" void franka_T_5_fun_decref(void);
extern "C" casadi_int franka_T_5_fun_n_in(void);
extern "C" casadi_int franka_T_5_fun_n_out(void);
extern "C" casadi_real franka_T_5_fun_default_in(casadi_int i);
extern "C" const char* franka_T_5_fun_name_in(casadi_int i);
extern "C" const char* franka_T_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_5_fun_SZ_ARG 1
#define franka_T_5_fun_SZ_RES 1
#define franka_T_5_fun_SZ_IW 0
#define franka_T_5_fun_SZ_W 4
extern "C" int franka_T_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_6_fun_alloc_mem(void);
extern "C" int franka_T_6_fun_init_mem(int mem);
extern "C" void franka_T_6_fun_free_mem(int mem);
extern "C" int franka_T_6_fun_checkout(void);
extern "C" void franka_T_6_fun_release(int mem);
extern "C" void franka_T_6_fun_incref(void);
extern "C" void franka_T_6_fun_decref(void);
extern "C" casadi_int franka_T_6_fun_n_in(void);
extern "C" casadi_int franka_T_6_fun_n_out(void);
extern "C" casadi_real franka_T_6_fun_default_in(casadi_int i);
extern "C" const char* franka_T_6_fun_name_in(casadi_int i);
extern "C" const char* franka_T_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_6_fun_SZ_ARG 1
#define franka_T_6_fun_SZ_RES 1
#define franka_T_6_fun_SZ_IW 0
#define franka_T_6_fun_SZ_W 4
extern "C" int franka_T_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_7_fun_alloc_mem(void);
extern "C" int franka_T_7_fun_init_mem(int mem);
extern "C" void franka_T_7_fun_free_mem(int mem);
extern "C" int franka_T_7_fun_checkout(void);
extern "C" void franka_T_7_fun_release(int mem);
extern "C" void franka_T_7_fun_incref(void);
extern "C" void franka_T_7_fun_decref(void);
extern "C" casadi_int franka_T_7_fun_n_in(void);
extern "C" casadi_int franka_T_7_fun_n_out(void);
extern "C" casadi_real franka_T_7_fun_default_in(casadi_int i);
extern "C" const char* franka_T_7_fun_name_in(casadi_int i);
extern "C" const char* franka_T_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_7_fun_SZ_ARG 1
#define franka_T_7_fun_SZ_RES 1
#define franka_T_7_fun_SZ_IW 0
#define franka_T_7_fun_SZ_W 4
extern "C" int franka_Yr_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_Yr_fun_alloc_mem(void);
extern "C" int franka_Yr_fun_init_mem(int mem);
extern "C" void franka_Yr_fun_free_mem(int mem);
extern "C" int franka_Yr_fun_checkout(void);
extern "C" void franka_Yr_fun_release(int mem);
extern "C" void franka_Yr_fun_incref(void);
extern "C" void franka_Yr_fun_decref(void);
extern "C" casadi_int franka_Yr_fun_n_in(void);
extern "C" casadi_int franka_Yr_fun_n_out(void);
extern "C" casadi_real franka_Yr_fun_default_in(casadi_int i);
extern "C" const char* franka_Yr_fun_name_in(casadi_int i);
extern "C" const char* franka_Yr_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_Yr_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_Yr_fun_sparsity_out(casadi_int i);
extern "C" int franka_Yr_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_Yr_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_Yr_fun_SZ_ARG 4
#define franka_Yr_fun_SZ_RES 1
#define franka_Yr_fun_SZ_IW 0
#define franka_Yr_fun_SZ_W 487
extern "C" int franka_reg_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_C_fun_alloc_mem(void);
extern "C" int franka_reg_C_fun_init_mem(int mem);
extern "C" void franka_reg_C_fun_free_mem(int mem);
extern "C" int franka_reg_C_fun_checkout(void);
extern "C" void franka_reg_C_fun_release(int mem);
extern "C" void franka_reg_C_fun_incref(void);
extern "C" void franka_reg_C_fun_decref(void);
extern "C" casadi_int franka_reg_C_fun_n_in(void);
extern "C" casadi_int franka_reg_C_fun_n_out(void);
extern "C" casadi_real franka_reg_C_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_C_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_C_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_C_fun_SZ_ARG 3
#define franka_reg_C_fun_SZ_RES 1
#define franka_reg_C_fun_SZ_IW 0
#define franka_reg_C_fun_SZ_W 464
extern "C" int franka_reg_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_G_fun_alloc_mem(void);
extern "C" int franka_reg_G_fun_init_mem(int mem);
extern "C" void franka_reg_G_fun_free_mem(int mem);
extern "C" int franka_reg_G_fun_checkout(void);
extern "C" void franka_reg_G_fun_release(int mem);
extern "C" void franka_reg_G_fun_incref(void);
extern "C" void franka_reg_G_fun_decref(void);
extern "C" casadi_int franka_reg_G_fun_n_in(void);
extern "C" casadi_int franka_reg_G_fun_n_out(void);
extern "C" casadi_real franka_reg_G_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_G_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_G_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_G_fun_SZ_ARG 1
#define franka_reg_G_fun_SZ_RES 1
#define franka_reg_G_fun_SZ_IW 0
#define franka_reg_G_fun_SZ_W 69
extern "C" int franka_reg_JTw_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_JTw_fun_alloc_mem(void);
extern "C" int franka_reg_JTw_fun_init_mem(int mem);
extern "C" void franka_reg_JTw_fun_free_mem(int mem);
extern "C" int franka_reg_JTw_fun_checkout(void);
extern "C" void franka_reg_JTw_fun_release(int mem);
extern "C" void franka_reg_JTw_fun_incref(void);
extern "C" void franka_reg_JTw_fun_decref(void);
extern "C" casadi_int franka_reg_JTw_fun_n_in(void);
extern "C" casadi_int franka_reg_JTw_fun_n_out(void);
extern "C" casadi_real franka_reg_JTw_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_JTw_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_JTw_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_JTw_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_JTw_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_JTw_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_JTw_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_JTw_fun_SZ_ARG 3
#define franka_reg_JTw_fun_SZ_RES 1
#define franka_reg_JTw_fun_SZ_IW 0
#define franka_reg_JTw_fun_SZ_W 56
extern "C" int franka_reg_Jdq_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_Jdq_fun_alloc_mem(void);
extern "C" int franka_reg_Jdq_fun_init_mem(int mem);
extern "C" void franka_reg_Jdq_fun_free_mem(int mem);
extern "C" int franka_reg_Jdq_fun_checkout(void);
extern "C" void franka_reg_Jdq_fun_release(int mem);
extern "C" void franka_reg_Jdq_fun_incref(void);
extern "C" void franka_reg_Jdq_fun_decref(void);
extern "C" casadi_int franka_reg_Jdq_fun_n_in(void);
extern "C" casadi_int franka_reg_Jdq_fun_n_out(void);
extern "C" casadi_real franka_reg_Jdq_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_Jdq_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_Jdq_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_Jdq_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_Jdq_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_Jdq_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_Jdq_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_Jdq_fun_SZ_ARG 3
#define franka_reg_Jdq_fun_SZ_RES 1
#define franka_reg_Jdq_fun_SZ_IW 0
#define franka_reg_Jdq_fun_SZ_W 52
extern "C" int franka_reg_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_M_fun_alloc_mem(void);
extern "C" int franka_reg_M_fun_init_mem(int mem);
extern "C" void franka_reg_M_fun_free_mem(int mem);
extern "C" int franka_reg_M_fun_checkout(void);
extern "C" void franka_reg_M_fun_release(int mem);
extern "C" void franka_reg_M_fun_incref(void);
extern "C" void franka_reg_M_fun_decref(void);
extern "C" casadi_int franka_reg_M_fun_n_in(void);
extern "C" casadi_int franka_reg_M_fun_n_out(void);
extern "C" casadi_real franka_reg_M_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_M_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_M_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_M_fun_SZ_ARG 2
#define franka_reg_M_fun_SZ_RES 1
#define franka_reg_M_fun_SZ_IW 0
#define franka_reg_M_fun_SZ_W 62
