/* This file was automatically generated by CasADi 3.7.2+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int franka_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_fun_checkout(void);
extern "C" void franka_C_fun_release(int mem);
extern "C" void franka_C_fun_incref(void);
extern "C" void franka_C_fun_decref(void);
extern "C" casadi_int franka_C_fun_n_in(void);
extern "C" casadi_int franka_C_fun_n_out(void);
extern "C" casadi_real franka_C_fun_default_in(casadi_int i);
extern "C" const char* franka_C_fun_name_in(casadi_int i);
extern "C" const char* franka_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_fun_SZ_ARG 5
#define franka_C_fun_SZ_RES 1
#define franka_C_fun_SZ_IW 0
#define franka_C_fun_SZ_W 0
extern "C" int franka_C_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_ddot_fun_checkout(void);
extern "C" void franka_C_ddot_fun_release(int mem);
extern "C" void franka_C_ddot_fun_incref(void);
extern "C" void franka_C_ddot_fun_decref(void);
extern "C" casadi_int franka_C_ddot_fun_n_in(void);
extern "C" casadi_int franka_C_ddot_fun_n_out(void);
extern "C" casadi_real franka_C_ddot_fun_default_in(casadi_int i);
extern "C" const char* franka_C_ddot_fun_name_in(casadi_int i);
extern "C" const char* franka_C_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_ddot_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_ddot_fun_SZ_ARG 7
#define franka_C_ddot_fun_SZ_RES 1
#define franka_C_ddot_fun_SZ_IW 0
#define franka_C_ddot_fun_SZ_W 0
extern "C" int franka_C_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_dot_fun_checkout(void);
extern "C" void franka_C_dot_fun_release(int mem);
extern "C" void franka_C_dot_fun_incref(void);
extern "C" void franka_C_dot_fun_decref(void);
extern "C" casadi_int franka_C_dot_fun_n_in(void);
extern "C" casadi_int franka_C_dot_fun_n_out(void);
extern "C" casadi_real franka_C_dot_fun_default_in(casadi_int i);
extern "C" const char* franka_C_dot_fun_name_in(casadi_int i);
extern "C" const char* franka_C_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_dot_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_dot_fun_SZ_ARG 6
#define franka_C_dot_fun_SZ_RES 1
#define franka_C_dot_fun_SZ_IW 0
#define franka_C_dot_fun_SZ_W 0
extern "C" int franka_C_std_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_C_std_fun_checkout(void);
extern "C" void franka_C_std_fun_release(int mem);
extern "C" void franka_C_std_fun_incref(void);
extern "C" void franka_C_std_fun_decref(void);
extern "C" casadi_int franka_C_std_fun_n_in(void);
extern "C" casadi_int franka_C_std_fun_n_out(void);
extern "C" casadi_real franka_C_std_fun_default_in(casadi_int i);
extern "C" const char* franka_C_std_fun_name_in(casadi_int i);
extern "C" const char* franka_C_std_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_C_std_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_C_std_fun_sparsity_out(casadi_int i);
extern "C" int franka_C_std_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_C_std_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_C_std_fun_SZ_ARG 5
#define franka_C_std_fun_SZ_RES 1
#define franka_C_std_fun_SZ_IW 0
#define franka_C_std_fun_SZ_W 0
extern "C" int franka_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_G_fun_checkout(void);
extern "C" void franka_G_fun_release(int mem);
extern "C" void franka_G_fun_incref(void);
extern "C" void franka_G_fun_decref(void);
extern "C" casadi_int franka_G_fun_n_in(void);
extern "C" casadi_int franka_G_fun_n_out(void);
extern "C" casadi_real franka_G_fun_default_in(casadi_int i);
extern "C" const char* franka_G_fun_name_in(casadi_int i);
extern "C" const char* franka_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_G_fun_sparsity_out(casadi_int i);
extern "C" int franka_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_G_fun_SZ_ARG 4
#define franka_G_fun_SZ_RES 1
#define franka_G_fun_SZ_IW 0
#define franka_G_fun_SZ_W 0
extern "C" int franka_G_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_G_ddot_fun_checkout(void);
extern "C" void franka_G_ddot_fun_release(int mem);
extern "C" void franka_G_ddot_fun_incref(void);
extern "C" void franka_G_ddot_fun_decref(void);
extern "C" casadi_int franka_G_ddot_fun_n_in(void);
extern "C" casadi_int franka_G_ddot_fun_n_out(void);
extern "C" casadi_real franka_G_ddot_fun_default_in(casadi_int i);
extern "C" const char* franka_G_ddot_fun_name_in(casadi_int i);
extern "C" const char* franka_G_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_G_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_G_ddot_fun_sparsity_out(casadi_int i);
extern "C" int franka_G_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_G_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_G_ddot_fun_SZ_ARG 6
#define franka_G_ddot_fun_SZ_RES 1
#define franka_G_ddot_fun_SZ_IW 0
#define franka_G_ddot_fun_SZ_W 0
extern "C" int franka_G_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_G_dot_fun_checkout(void);
extern "C" void franka_G_dot_fun_release(int mem);
extern "C" void franka_G_dot_fun_incref(void);
extern "C" void franka_G_dot_fun_decref(void);
extern "C" casadi_int franka_G_dot_fun_n_in(void);
extern "C" casadi_int franka_G_dot_fun_n_out(void);
extern "C" casadi_real franka_G_dot_fun_default_in(casadi_int i);
extern "C" const char* franka_G_dot_fun_name_in(casadi_int i);
extern "C" const char* franka_G_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_G_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_G_dot_fun_sparsity_out(casadi_int i);
extern "C" int franka_G_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_G_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_G_dot_fun_SZ_ARG 5
#define franka_G_dot_fun_SZ_RES 1
#define franka_G_dot_fun_SZ_IW 0
#define franka_G_dot_fun_SZ_W 0
extern "C" int franka_J_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_0_fun_checkout(void);
extern "C" void franka_J_0_fun_release(int mem);
extern "C" void franka_J_0_fun_incref(void);
extern "C" void franka_J_0_fun_decref(void);
extern "C" casadi_int franka_J_0_fun_n_in(void);
extern "C" casadi_int franka_J_0_fun_n_out(void);
extern "C" casadi_real franka_J_0_fun_default_in(casadi_int i);
extern "C" const char* franka_J_0_fun_name_in(casadi_int i);
extern "C" const char* franka_J_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_0_fun_SZ_ARG 3
#define franka_J_0_fun_SZ_RES 1
#define franka_J_0_fun_SZ_IW 0
#define franka_J_0_fun_SZ_W 0
extern "C" int franka_J_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_1_fun_checkout(void);
extern "C" void franka_J_1_fun_release(int mem);
extern "C" void franka_J_1_fun_incref(void);
extern "C" void franka_J_1_fun_decref(void);
extern "C" casadi_int franka_J_1_fun_n_in(void);
extern "C" casadi_int franka_J_1_fun_n_out(void);
extern "C" casadi_real franka_J_1_fun_default_in(casadi_int i);
extern "C" const char* franka_J_1_fun_name_in(casadi_int i);
extern "C" const char* franka_J_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_1_fun_SZ_ARG 3
#define franka_J_1_fun_SZ_RES 1
#define franka_J_1_fun_SZ_IW 0
#define franka_J_1_fun_SZ_W 0
extern "C" int franka_J_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_2_fun_checkout(void);
extern "C" void franka_J_2_fun_release(int mem);
extern "C" void franka_J_2_fun_incref(void);
extern "C" void franka_J_2_fun_decref(void);
extern "C" casadi_int franka_J_2_fun_n_in(void);
extern "C" casadi_int franka_J_2_fun_n_out(void);
extern "C" casadi_real franka_J_2_fun_default_in(casadi_int i);
extern "C" const char* franka_J_2_fun_name_in(casadi_int i);
extern "C" const char* franka_J_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_2_fun_SZ_ARG 3
#define franka_J_2_fun_SZ_RES 1
#define franka_J_2_fun_SZ_IW 0
#define franka_J_2_fun_SZ_W 0
extern "C" int franka_J_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_3_fun_checkout(void);
extern "C" void franka_J_3_fun_release(int mem);
extern "C" void franka_J_3_fun_incref(void);
extern "C" void franka_J_3_fun_decref(void);
extern "C" casadi_int franka_J_3_fun_n_in(void);
extern "C" casadi_int franka_J_3_fun_n_out(void);
extern "C" casadi_real franka_J_3_fun_default_in(casadi_int i);
extern "C" const char* franka_J_3_fun_name_in(casadi_int i);
extern "C" const char* franka_J_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_3_fun_SZ_ARG 3
#define franka_J_3_fun_SZ_RES 1
#define franka_J_3_fun_SZ_IW 0
#define franka_J_3_fun_SZ_W 0
extern "C" int franka_J_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_4_fun_checkout(void);
extern "C" void franka_J_4_fun_release(int mem);
extern "C" void franka_J_4_fun_incref(void);
extern "C" void franka_J_4_fun_decref(void);
extern "C" casadi_int franka_J_4_fun_n_in(void);
extern "C" casadi_int franka_J_4_fun_n_out(void);
extern "C" casadi_real franka_J_4_fun_default_in(casadi_int i);
extern "C" const char* franka_J_4_fun_name_in(casadi_int i);
extern "C" const char* franka_J_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_4_fun_SZ_ARG 3
#define franka_J_4_fun_SZ_RES 1
#define franka_J_4_fun_SZ_IW 0
#define franka_J_4_fun_SZ_W 0
extern "C" int franka_J_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_5_fun_checkout(void);
extern "C" void franka_J_5_fun_release(int mem);
extern "C" void franka_J_5_fun_incref(void);
extern "C" void franka_J_5_fun_decref(void);
extern "C" casadi_int franka_J_5_fun_n_in(void);
extern "C" casadi_int franka_J_5_fun_n_out(void);
extern "C" casadi_real franka_J_5_fun_default_in(casadi_int i);
extern "C" const char* franka_J_5_fun_name_in(casadi_int i);
extern "C" const char* franka_J_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_5_fun_SZ_ARG 3
#define franka_J_5_fun_SZ_RES 1
#define franka_J_5_fun_SZ_IW 0
#define franka_J_5_fun_SZ_W 0
extern "C" int franka_J_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_6_fun_checkout(void);
extern "C" void franka_J_6_fun_release(int mem);
extern "C" void franka_J_6_fun_incref(void);
extern "C" void franka_J_6_fun_decref(void);
extern "C" casadi_int franka_J_6_fun_n_in(void);
extern "C" casadi_int franka_J_6_fun_n_out(void);
extern "C" casadi_real franka_J_6_fun_default_in(casadi_int i);
extern "C" const char* franka_J_6_fun_name_in(casadi_int i);
extern "C" const char* franka_J_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_6_fun_SZ_ARG 3
#define franka_J_6_fun_SZ_RES 1
#define franka_J_6_fun_SZ_IW 0
#define franka_J_6_fun_SZ_W 0
extern "C" int franka_J_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_7_fun_checkout(void);
extern "C" void franka_J_7_fun_release(int mem);
extern "C" void franka_J_7_fun_incref(void);
extern "C" void franka_J_7_fun_decref(void);
extern "C" casadi_int franka_J_7_fun_n_in(void);
extern "C" casadi_int franka_J_7_fun_n_out(void);
extern "C" casadi_real franka_J_7_fun_default_in(casadi_int i);
extern "C" const char* franka_J_7_fun_name_in(casadi_int i);
extern "C" const char* franka_J_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_7_fun_SZ_ARG 3
#define franka_J_7_fun_SZ_RES 1
#define franka_J_7_fun_SZ_IW 0
#define franka_J_7_fun_SZ_W 0
extern "C" int franka_J_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_8_fun_checkout(void);
extern "C" void franka_J_8_fun_release(int mem);
extern "C" void franka_J_8_fun_incref(void);
extern "C" void franka_J_8_fun_decref(void);
extern "C" casadi_int franka_J_8_fun_n_in(void);
extern "C" casadi_int franka_J_8_fun_n_out(void);
extern "C" casadi_real franka_J_8_fun_default_in(casadi_int i);
extern "C" const char* franka_J_8_fun_name_in(casadi_int i);
extern "C" const char* franka_J_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_8_fun_SZ_ARG 3
#define franka_J_8_fun_SZ_RES 1
#define franka_J_8_fun_SZ_IW 0
#define franka_J_8_fun_SZ_W 0
extern "C" int franka_J_EE_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_EE_fun_checkout(void);
extern "C" void franka_J_EE_fun_release(int mem);
extern "C" void franka_J_EE_fun_incref(void);
extern "C" void franka_J_EE_fun_decref(void);
extern "C" casadi_int franka_J_EE_fun_n_in(void);
extern "C" casadi_int franka_J_EE_fun_n_out(void);
extern "C" casadi_real franka_J_EE_fun_default_in(casadi_int i);
extern "C" const char* franka_J_EE_fun_name_in(casadi_int i);
extern "C" const char* franka_J_EE_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_EE_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_EE_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_EE_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_EE_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_EE_fun_SZ_ARG 3
#define franka_J_EE_fun_SZ_RES 1
#define franka_J_EE_fun_SZ_IW 0
#define franka_J_EE_fun_SZ_W 0
extern "C" int franka_J_EE_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_EE_ddot_fun_checkout(void);
extern "C" void franka_J_EE_ddot_fun_release(int mem);
extern "C" void franka_J_EE_ddot_fun_incref(void);
extern "C" void franka_J_EE_ddot_fun_decref(void);
extern "C" casadi_int franka_J_EE_ddot_fun_n_in(void);
extern "C" casadi_int franka_J_EE_ddot_fun_n_out(void);
extern "C" casadi_real franka_J_EE_ddot_fun_default_in(casadi_int i);
extern "C" const char* franka_J_EE_ddot_fun_name_in(casadi_int i);
extern "C" const char* franka_J_EE_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_EE_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_EE_ddot_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_EE_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_EE_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_EE_ddot_fun_SZ_ARG 5
#define franka_J_EE_ddot_fun_SZ_RES 1
#define franka_J_EE_ddot_fun_SZ_IW 0
#define franka_J_EE_ddot_fun_SZ_W 0
extern "C" int franka_J_EE_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_EE_dot_fun_checkout(void);
extern "C" void franka_J_EE_dot_fun_release(int mem);
extern "C" void franka_J_EE_dot_fun_incref(void);
extern "C" void franka_J_EE_dot_fun_decref(void);
extern "C" casadi_int franka_J_EE_dot_fun_n_in(void);
extern "C" casadi_int franka_J_EE_dot_fun_n_out(void);
extern "C" casadi_real franka_J_EE_dot_fun_default_in(casadi_int i);
extern "C" const char* franka_J_EE_dot_fun_name_in(casadi_int i);
extern "C" const char* franka_J_EE_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_EE_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_EE_dot_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_EE_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_EE_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_EE_dot_fun_SZ_ARG 4
#define franka_J_EE_dot_fun_SZ_RES 1
#define franka_J_EE_dot_fun_SZ_IW 0
#define franka_J_EE_dot_fun_SZ_W 0
extern "C" int franka_J_EE_pinv_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_EE_pinv_fun_checkout(void);
extern "C" void franka_J_EE_pinv_fun_release(int mem);
extern "C" void franka_J_EE_pinv_fun_incref(void);
extern "C" void franka_J_EE_pinv_fun_decref(void);
extern "C" casadi_int franka_J_EE_pinv_fun_n_in(void);
extern "C" casadi_int franka_J_EE_pinv_fun_n_out(void);
extern "C" casadi_real franka_J_EE_pinv_fun_default_in(casadi_int i);
extern "C" const char* franka_J_EE_pinv_fun_name_in(casadi_int i);
extern "C" const char* franka_J_EE_pinv_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_EE_pinv_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_EE_pinv_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_EE_pinv_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_EE_pinv_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_EE_pinv_fun_SZ_ARG 3
#define franka_J_EE_pinv_fun_SZ_RES 1
#define franka_J_EE_pinv_fun_SZ_IW 0
#define franka_J_EE_pinv_fun_SZ_W 0
extern "C" int franka_J_cm_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_0_fun_checkout(void);
extern "C" void franka_J_cm_0_fun_release(int mem);
extern "C" void franka_J_cm_0_fun_incref(void);
extern "C" void franka_J_cm_0_fun_decref(void);
extern "C" casadi_int franka_J_cm_0_fun_n_in(void);
extern "C" casadi_int franka_J_cm_0_fun_n_out(void);
extern "C" casadi_real franka_J_cm_0_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_0_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_0_fun_SZ_ARG 4
#define franka_J_cm_0_fun_SZ_RES 1
#define franka_J_cm_0_fun_SZ_IW 0
#define franka_J_cm_0_fun_SZ_W 0
extern "C" int franka_J_cm_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_1_fun_checkout(void);
extern "C" void franka_J_cm_1_fun_release(int mem);
extern "C" void franka_J_cm_1_fun_incref(void);
extern "C" void franka_J_cm_1_fun_decref(void);
extern "C" casadi_int franka_J_cm_1_fun_n_in(void);
extern "C" casadi_int franka_J_cm_1_fun_n_out(void);
extern "C" casadi_real franka_J_cm_1_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_1_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_1_fun_SZ_ARG 4
#define franka_J_cm_1_fun_SZ_RES 1
#define franka_J_cm_1_fun_SZ_IW 0
#define franka_J_cm_1_fun_SZ_W 0
extern "C" int franka_J_cm_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_2_fun_checkout(void);
extern "C" void franka_J_cm_2_fun_release(int mem);
extern "C" void franka_J_cm_2_fun_incref(void);
extern "C" void franka_J_cm_2_fun_decref(void);
extern "C" casadi_int franka_J_cm_2_fun_n_in(void);
extern "C" casadi_int franka_J_cm_2_fun_n_out(void);
extern "C" casadi_real franka_J_cm_2_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_2_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_2_fun_SZ_ARG 4
#define franka_J_cm_2_fun_SZ_RES 1
#define franka_J_cm_2_fun_SZ_IW 0
#define franka_J_cm_2_fun_SZ_W 0
extern "C" int franka_J_cm_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_3_fun_checkout(void);
extern "C" void franka_J_cm_3_fun_release(int mem);
extern "C" void franka_J_cm_3_fun_incref(void);
extern "C" void franka_J_cm_3_fun_decref(void);
extern "C" casadi_int franka_J_cm_3_fun_n_in(void);
extern "C" casadi_int franka_J_cm_3_fun_n_out(void);
extern "C" casadi_real franka_J_cm_3_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_3_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_3_fun_SZ_ARG 4
#define franka_J_cm_3_fun_SZ_RES 1
#define franka_J_cm_3_fun_SZ_IW 0
#define franka_J_cm_3_fun_SZ_W 0
extern "C" int franka_J_cm_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_4_fun_checkout(void);
extern "C" void franka_J_cm_4_fun_release(int mem);
extern "C" void franka_J_cm_4_fun_incref(void);
extern "C" void franka_J_cm_4_fun_decref(void);
extern "C" casadi_int franka_J_cm_4_fun_n_in(void);
extern "C" casadi_int franka_J_cm_4_fun_n_out(void);
extern "C" casadi_real franka_J_cm_4_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_4_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_4_fun_SZ_ARG 4
#define franka_J_cm_4_fun_SZ_RES 1
#define franka_J_cm_4_fun_SZ_IW 0
#define franka_J_cm_4_fun_SZ_W 0
extern "C" int franka_J_cm_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_5_fun_checkout(void);
extern "C" void franka_J_cm_5_fun_release(int mem);
extern "C" void franka_J_cm_5_fun_incref(void);
extern "C" void franka_J_cm_5_fun_decref(void);
extern "C" casadi_int franka_J_cm_5_fun_n_in(void);
extern "C" casadi_int franka_J_cm_5_fun_n_out(void);
extern "C" casadi_real franka_J_cm_5_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_5_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_5_fun_SZ_ARG 4
#define franka_J_cm_5_fun_SZ_RES 1
#define franka_J_cm_5_fun_SZ_IW 0
#define franka_J_cm_5_fun_SZ_W 0
extern "C" int franka_J_cm_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_6_fun_checkout(void);
extern "C" void franka_J_cm_6_fun_release(int mem);
extern "C" void franka_J_cm_6_fun_incref(void);
extern "C" void franka_J_cm_6_fun_decref(void);
extern "C" casadi_int franka_J_cm_6_fun_n_in(void);
extern "C" casadi_int franka_J_cm_6_fun_n_out(void);
extern "C" casadi_real franka_J_cm_6_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_6_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_6_fun_SZ_ARG 4
#define franka_J_cm_6_fun_SZ_RES 1
#define franka_J_cm_6_fun_SZ_IW 0
#define franka_J_cm_6_fun_SZ_W 0
extern "C" int franka_J_cm_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_7_fun_checkout(void);
extern "C" void franka_J_cm_7_fun_release(int mem);
extern "C" void franka_J_cm_7_fun_incref(void);
extern "C" void franka_J_cm_7_fun_decref(void);
extern "C" casadi_int franka_J_cm_7_fun_n_in(void);
extern "C" casadi_int franka_J_cm_7_fun_n_out(void);
extern "C" casadi_real franka_J_cm_7_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_7_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_7_fun_SZ_ARG 4
#define franka_J_cm_7_fun_SZ_RES 1
#define franka_J_cm_7_fun_SZ_IW 0
#define franka_J_cm_7_fun_SZ_W 0
extern "C" int franka_J_cm_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_J_cm_8_fun_checkout(void);
extern "C" void franka_J_cm_8_fun_release(int mem);
extern "C" void franka_J_cm_8_fun_incref(void);
extern "C" void franka_J_cm_8_fun_decref(void);
extern "C" casadi_int franka_J_cm_8_fun_n_in(void);
extern "C" casadi_int franka_J_cm_8_fun_n_out(void);
extern "C" casadi_real franka_J_cm_8_fun_default_in(casadi_int i);
extern "C" const char* franka_J_cm_8_fun_name_in(casadi_int i);
extern "C" const char* franka_J_cm_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_J_cm_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_J_cm_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_J_cm_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_J_cm_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_J_cm_8_fun_SZ_ARG 4
#define franka_J_cm_8_fun_SZ_RES 1
#define franka_J_cm_8_fun_SZ_IW 0
#define franka_J_cm_8_fun_SZ_W 0
extern "C" int franka_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_M_fun_checkout(void);
extern "C" void franka_M_fun_release(int mem);
extern "C" void franka_M_fun_incref(void);
extern "C" void franka_M_fun_decref(void);
extern "C" casadi_int franka_M_fun_n_in(void);
extern "C" casadi_int franka_M_fun_n_out(void);
extern "C" casadi_real franka_M_fun_default_in(casadi_int i);
extern "C" const char* franka_M_fun_name_in(casadi_int i);
extern "C" const char* franka_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_M_fun_sparsity_out(casadi_int i);
extern "C" int franka_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_M_fun_SZ_ARG 4
#define franka_M_fun_SZ_RES 1
#define franka_M_fun_SZ_IW 0
#define franka_M_fun_SZ_W 0
extern "C" int franka_M_ddot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_M_ddot_fun_checkout(void);
extern "C" void franka_M_ddot_fun_release(int mem);
extern "C" void franka_M_ddot_fun_incref(void);
extern "C" void franka_M_ddot_fun_decref(void);
extern "C" casadi_int franka_M_ddot_fun_n_in(void);
extern "C" casadi_int franka_M_ddot_fun_n_out(void);
extern "C" casadi_real franka_M_ddot_fun_default_in(casadi_int i);
extern "C" const char* franka_M_ddot_fun_name_in(casadi_int i);
extern "C" const char* franka_M_ddot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_M_ddot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_M_ddot_fun_sparsity_out(casadi_int i);
extern "C" int franka_M_ddot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_M_ddot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_M_ddot_fun_SZ_ARG 6
#define franka_M_ddot_fun_SZ_RES 1
#define franka_M_ddot_fun_SZ_IW 0
#define franka_M_ddot_fun_SZ_W 0
extern "C" int franka_M_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_M_dot_fun_checkout(void);
extern "C" void franka_M_dot_fun_release(int mem);
extern "C" void franka_M_dot_fun_incref(void);
extern "C" void franka_M_dot_fun_decref(void);
extern "C" casadi_int franka_M_dot_fun_n_in(void);
extern "C" casadi_int franka_M_dot_fun_n_out(void);
extern "C" casadi_real franka_M_dot_fun_default_in(casadi_int i);
extern "C" const char* franka_M_dot_fun_name_in(casadi_int i);
extern "C" const char* franka_M_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_M_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_M_dot_fun_sparsity_out(casadi_int i);
extern "C" int franka_M_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_M_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_M_dot_fun_SZ_ARG 5
#define franka_M_dot_fun_SZ_RES 1
#define franka_M_dot_fun_SZ_IW 0
#define franka_M_dot_fun_SZ_W 0
extern "C" int franka_T_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_0_fun_checkout(void);
extern "C" void franka_T_0_fun_release(int mem);
extern "C" void franka_T_0_fun_incref(void);
extern "C" void franka_T_0_fun_decref(void);
extern "C" casadi_int franka_T_0_fun_n_in(void);
extern "C" casadi_int franka_T_0_fun_n_out(void);
extern "C" casadi_real franka_T_0_fun_default_in(casadi_int i);
extern "C" const char* franka_T_0_fun_name_in(casadi_int i);
extern "C" const char* franka_T_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_0_fun_SZ_ARG 3
#define franka_T_0_fun_SZ_RES 1
#define franka_T_0_fun_SZ_IW 0
#define franka_T_0_fun_SZ_W 0
extern "C" int franka_T_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_1_fun_checkout(void);
extern "C" void franka_T_1_fun_release(int mem);
extern "C" void franka_T_1_fun_incref(void);
extern "C" void franka_T_1_fun_decref(void);
extern "C" casadi_int franka_T_1_fun_n_in(void);
extern "C" casadi_int franka_T_1_fun_n_out(void);
extern "C" casadi_real franka_T_1_fun_default_in(casadi_int i);
extern "C" const char* franka_T_1_fun_name_in(casadi_int i);
extern "C" const char* franka_T_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_1_fun_SZ_ARG 3
#define franka_T_1_fun_SZ_RES 1
#define franka_T_1_fun_SZ_IW 0
#define franka_T_1_fun_SZ_W 0
extern "C" int franka_T_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_2_fun_checkout(void);
extern "C" void franka_T_2_fun_release(int mem);
extern "C" void franka_T_2_fun_incref(void);
extern "C" void franka_T_2_fun_decref(void);
extern "C" casadi_int franka_T_2_fun_n_in(void);
extern "C" casadi_int franka_T_2_fun_n_out(void);
extern "C" casadi_real franka_T_2_fun_default_in(casadi_int i);
extern "C" const char* franka_T_2_fun_name_in(casadi_int i);
extern "C" const char* franka_T_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_2_fun_SZ_ARG 3
#define franka_T_2_fun_SZ_RES 1
#define franka_T_2_fun_SZ_IW 0
#define franka_T_2_fun_SZ_W 0
extern "C" int franka_T_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_3_fun_checkout(void);
extern "C" void franka_T_3_fun_release(int mem);
extern "C" void franka_T_3_fun_incref(void);
extern "C" void franka_T_3_fun_decref(void);
extern "C" casadi_int franka_T_3_fun_n_in(void);
extern "C" casadi_int franka_T_3_fun_n_out(void);
extern "C" casadi_real franka_T_3_fun_default_in(casadi_int i);
extern "C" const char* franka_T_3_fun_name_in(casadi_int i);
extern "C" const char* franka_T_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_3_fun_SZ_ARG 3
#define franka_T_3_fun_SZ_RES 1
#define franka_T_3_fun_SZ_IW 0
#define franka_T_3_fun_SZ_W 0
extern "C" int franka_T_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_4_fun_checkout(void);
extern "C" void franka_T_4_fun_release(int mem);
extern "C" void franka_T_4_fun_incref(void);
extern "C" void franka_T_4_fun_decref(void);
extern "C" casadi_int franka_T_4_fun_n_in(void);
extern "C" casadi_int franka_T_4_fun_n_out(void);
extern "C" casadi_real franka_T_4_fun_default_in(casadi_int i);
extern "C" const char* franka_T_4_fun_name_in(casadi_int i);
extern "C" const char* franka_T_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_4_fun_SZ_ARG 3
#define franka_T_4_fun_SZ_RES 1
#define franka_T_4_fun_SZ_IW 0
#define franka_T_4_fun_SZ_W 0
extern "C" int franka_T_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_5_fun_checkout(void);
extern "C" void franka_T_5_fun_release(int mem);
extern "C" void franka_T_5_fun_incref(void);
extern "C" void franka_T_5_fun_decref(void);
extern "C" casadi_int franka_T_5_fun_n_in(void);
extern "C" casadi_int franka_T_5_fun_n_out(void);
extern "C" casadi_real franka_T_5_fun_default_in(casadi_int i);
extern "C" const char* franka_T_5_fun_name_in(casadi_int i);
extern "C" const char* franka_T_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_5_fun_SZ_ARG 3
#define franka_T_5_fun_SZ_RES 1
#define franka_T_5_fun_SZ_IW 0
#define franka_T_5_fun_SZ_W 0
extern "C" int franka_T_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_6_fun_checkout(void);
extern "C" void franka_T_6_fun_release(int mem);
extern "C" void franka_T_6_fun_incref(void);
extern "C" void franka_T_6_fun_decref(void);
extern "C" casadi_int franka_T_6_fun_n_in(void);
extern "C" casadi_int franka_T_6_fun_n_out(void);
extern "C" casadi_real franka_T_6_fun_default_in(casadi_int i);
extern "C" const char* franka_T_6_fun_name_in(casadi_int i);
extern "C" const char* franka_T_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_6_fun_SZ_ARG 3
#define franka_T_6_fun_SZ_RES 1
#define franka_T_6_fun_SZ_IW 0
#define franka_T_6_fun_SZ_W 0
extern "C" int franka_T_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_7_fun_checkout(void);
extern "C" void franka_T_7_fun_release(int mem);
extern "C" void franka_T_7_fun_incref(void);
extern "C" void franka_T_7_fun_decref(void);
extern "C" casadi_int franka_T_7_fun_n_in(void);
extern "C" casadi_int franka_T_7_fun_n_out(void);
extern "C" casadi_real franka_T_7_fun_default_in(casadi_int i);
extern "C" const char* franka_T_7_fun_name_in(casadi_int i);
extern "C" const char* franka_T_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_7_fun_SZ_ARG 3
#define franka_T_7_fun_SZ_RES 1
#define franka_T_7_fun_SZ_IW 0
#define franka_T_7_fun_SZ_W 0
extern "C" int franka_T_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_8_fun_checkout(void);
extern "C" void franka_T_8_fun_release(int mem);
extern "C" void franka_T_8_fun_incref(void);
extern "C" void franka_T_8_fun_decref(void);
extern "C" casadi_int franka_T_8_fun_n_in(void);
extern "C" casadi_int franka_T_8_fun_n_out(void);
extern "C" casadi_real franka_T_8_fun_default_in(casadi_int i);
extern "C" const char* franka_T_8_fun_name_in(casadi_int i);
extern "C" const char* franka_T_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_8_fun_SZ_ARG 3
#define franka_T_8_fun_SZ_RES 1
#define franka_T_8_fun_SZ_IW 0
#define franka_T_8_fun_SZ_W 0
extern "C" int franka_T_JOINT_FIXED_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_JOINT_FIXED_fun_checkout(void);
extern "C" void franka_T_JOINT_FIXED_fun_release(int mem);
extern "C" void franka_T_JOINT_FIXED_fun_incref(void);
extern "C" void franka_T_JOINT_FIXED_fun_decref(void);
extern "C" casadi_int franka_T_JOINT_FIXED_fun_n_in(void);
extern "C" casadi_int franka_T_JOINT_FIXED_fun_n_out(void);
extern "C" casadi_real franka_T_JOINT_FIXED_fun_default_in(casadi_int i);
extern "C" const char* franka_T_JOINT_FIXED_fun_name_in(casadi_int i);
extern "C" const char* franka_T_JOINT_FIXED_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_FIXED_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_FIXED_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_JOINT_FIXED_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_JOINT_FIXED_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_JOINT_FIXED_fun_SZ_ARG 2
#define franka_T_JOINT_FIXED_fun_SZ_RES 1
#define franka_T_JOINT_FIXED_fun_SZ_IW 0
#define franka_T_JOINT_FIXED_fun_SZ_W 0
extern "C" int franka_T_JOINT_P_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_JOINT_P_fun_checkout(void);
extern "C" void franka_T_JOINT_P_fun_release(int mem);
extern "C" void franka_T_JOINT_P_fun_incref(void);
extern "C" void franka_T_JOINT_P_fun_decref(void);
extern "C" casadi_int franka_T_JOINT_P_fun_n_in(void);
extern "C" casadi_int franka_T_JOINT_P_fun_n_out(void);
extern "C" casadi_real franka_T_JOINT_P_fun_default_in(casadi_int i);
extern "C" const char* franka_T_JOINT_P_fun_name_in(casadi_int i);
extern "C" const char* franka_T_JOINT_P_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_P_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_P_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_JOINT_P_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_JOINT_P_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_JOINT_P_fun_SZ_ARG 2
#define franka_T_JOINT_P_fun_SZ_RES 1
#define franka_T_JOINT_P_fun_SZ_IW 0
#define franka_T_JOINT_P_fun_SZ_W 0
extern "C" int franka_T_JOINT_R_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_JOINT_R_fun_checkout(void);
extern "C" void franka_T_JOINT_R_fun_release(int mem);
extern "C" void franka_T_JOINT_R_fun_incref(void);
extern "C" void franka_T_JOINT_R_fun_decref(void);
extern "C" casadi_int franka_T_JOINT_R_fun_n_in(void);
extern "C" casadi_int franka_T_JOINT_R_fun_n_out(void);
extern "C" casadi_real franka_T_JOINT_R_fun_default_in(casadi_int i);
extern "C" const char* franka_T_JOINT_R_fun_name_in(casadi_int i);
extern "C" const char* franka_T_JOINT_R_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_R_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_JOINT_R_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_JOINT_R_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_JOINT_R_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_JOINT_R_fun_SZ_ARG 2
#define franka_T_JOINT_R_fun_SZ_RES 1
#define franka_T_JOINT_R_fun_SZ_IW 0
#define franka_T_JOINT_R_fun_SZ_W 0
extern "C" int franka_T_w_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_0_fun_checkout(void);
extern "C" void franka_T_w_0_fun_release(int mem);
extern "C" void franka_T_w_0_fun_incref(void);
extern "C" void franka_T_w_0_fun_decref(void);
extern "C" casadi_int franka_T_w_0_fun_n_in(void);
extern "C" casadi_int franka_T_w_0_fun_n_out(void);
extern "C" casadi_real franka_T_w_0_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_0_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_0_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_0_fun_SZ_ARG 3
#define franka_T_w_0_fun_SZ_RES 1
#define franka_T_w_0_fun_SZ_IW 0
#define franka_T_w_0_fun_SZ_W 0
extern "C" int franka_T_w_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_1_fun_checkout(void);
extern "C" void franka_T_w_1_fun_release(int mem);
extern "C" void franka_T_w_1_fun_incref(void);
extern "C" void franka_T_w_1_fun_decref(void);
extern "C" casadi_int franka_T_w_1_fun_n_in(void);
extern "C" casadi_int franka_T_w_1_fun_n_out(void);
extern "C" casadi_real franka_T_w_1_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_1_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_1_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_1_fun_SZ_ARG 3
#define franka_T_w_1_fun_SZ_RES 1
#define franka_T_w_1_fun_SZ_IW 0
#define franka_T_w_1_fun_SZ_W 0
extern "C" int franka_T_w_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_2_fun_checkout(void);
extern "C" void franka_T_w_2_fun_release(int mem);
extern "C" void franka_T_w_2_fun_incref(void);
extern "C" void franka_T_w_2_fun_decref(void);
extern "C" casadi_int franka_T_w_2_fun_n_in(void);
extern "C" casadi_int franka_T_w_2_fun_n_out(void);
extern "C" casadi_real franka_T_w_2_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_2_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_2_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_2_fun_SZ_ARG 3
#define franka_T_w_2_fun_SZ_RES 1
#define franka_T_w_2_fun_SZ_IW 0
#define franka_T_w_2_fun_SZ_W 0
extern "C" int franka_T_w_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_3_fun_checkout(void);
extern "C" void franka_T_w_3_fun_release(int mem);
extern "C" void franka_T_w_3_fun_incref(void);
extern "C" void franka_T_w_3_fun_decref(void);
extern "C" casadi_int franka_T_w_3_fun_n_in(void);
extern "C" casadi_int franka_T_w_3_fun_n_out(void);
extern "C" casadi_real franka_T_w_3_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_3_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_3_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_3_fun_SZ_ARG 3
#define franka_T_w_3_fun_SZ_RES 1
#define franka_T_w_3_fun_SZ_IW 0
#define franka_T_w_3_fun_SZ_W 0
extern "C" int franka_T_w_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_4_fun_checkout(void);
extern "C" void franka_T_w_4_fun_release(int mem);
extern "C" void franka_T_w_4_fun_incref(void);
extern "C" void franka_T_w_4_fun_decref(void);
extern "C" casadi_int franka_T_w_4_fun_n_in(void);
extern "C" casadi_int franka_T_w_4_fun_n_out(void);
extern "C" casadi_real franka_T_w_4_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_4_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_4_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_4_fun_SZ_ARG 3
#define franka_T_w_4_fun_SZ_RES 1
#define franka_T_w_4_fun_SZ_IW 0
#define franka_T_w_4_fun_SZ_W 0
extern "C" int franka_T_w_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_5_fun_checkout(void);
extern "C" void franka_T_w_5_fun_release(int mem);
extern "C" void franka_T_w_5_fun_incref(void);
extern "C" void franka_T_w_5_fun_decref(void);
extern "C" casadi_int franka_T_w_5_fun_n_in(void);
extern "C" casadi_int franka_T_w_5_fun_n_out(void);
extern "C" casadi_real franka_T_w_5_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_5_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_5_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_5_fun_SZ_ARG 3
#define franka_T_w_5_fun_SZ_RES 1
#define franka_T_w_5_fun_SZ_IW 0
#define franka_T_w_5_fun_SZ_W 0
extern "C" int franka_T_w_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_6_fun_checkout(void);
extern "C" void franka_T_w_6_fun_release(int mem);
extern "C" void franka_T_w_6_fun_incref(void);
extern "C" void franka_T_w_6_fun_decref(void);
extern "C" casadi_int franka_T_w_6_fun_n_in(void);
extern "C" casadi_int franka_T_w_6_fun_n_out(void);
extern "C" casadi_real franka_T_w_6_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_6_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_6_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_6_fun_SZ_ARG 3
#define franka_T_w_6_fun_SZ_RES 1
#define franka_T_w_6_fun_SZ_IW 0
#define franka_T_w_6_fun_SZ_W 0
extern "C" int franka_T_w_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_7_fun_checkout(void);
extern "C" void franka_T_w_7_fun_release(int mem);
extern "C" void franka_T_w_7_fun_incref(void);
extern "C" void franka_T_w_7_fun_decref(void);
extern "C" casadi_int franka_T_w_7_fun_n_in(void);
extern "C" casadi_int franka_T_w_7_fun_n_out(void);
extern "C" casadi_real franka_T_w_7_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_7_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_7_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_7_fun_SZ_ARG 3
#define franka_T_w_7_fun_SZ_RES 1
#define franka_T_w_7_fun_SZ_IW 0
#define franka_T_w_7_fun_SZ_W 0
extern "C" int franka_T_w_8_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_8_fun_checkout(void);
extern "C" void franka_T_w_8_fun_release(int mem);
extern "C" void franka_T_w_8_fun_incref(void);
extern "C" void franka_T_w_8_fun_decref(void);
extern "C" casadi_int franka_T_w_8_fun_n_in(void);
extern "C" casadi_int franka_T_w_8_fun_n_out(void);
extern "C" casadi_real franka_T_w_8_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_8_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_8_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_8_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_8_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_8_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_8_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_8_fun_SZ_ARG 3
#define franka_T_w_8_fun_SZ_RES 1
#define franka_T_w_8_fun_SZ_IW 0
#define franka_T_w_8_fun_SZ_W 0
extern "C" int franka_T_w_EE_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_T_w_EE_fun_checkout(void);
extern "C" void franka_T_w_EE_fun_release(int mem);
extern "C" void franka_T_w_EE_fun_incref(void);
extern "C" void franka_T_w_EE_fun_decref(void);
extern "C" casadi_int franka_T_w_EE_fun_n_in(void);
extern "C" casadi_int franka_T_w_EE_fun_n_out(void);
extern "C" casadi_real franka_T_w_EE_fun_default_in(casadi_int i);
extern "C" const char* franka_T_w_EE_fun_name_in(casadi_int i);
extern "C" const char* franka_T_w_EE_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_T_w_EE_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_T_w_EE_fun_sparsity_out(casadi_int i);
extern "C" int franka_T_w_EE_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_T_w_EE_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_T_w_EE_fun_SZ_ARG 3
#define franka_T_w_EE_fun_SZ_RES 1
#define franka_T_w_EE_fun_SZ_IW 0
#define franka_T_w_EE_fun_SZ_W 0
extern "C" int franka_Yr_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_Yr_fun_checkout(void);
extern "C" void franka_Yr_fun_release(int mem);
extern "C" void franka_Yr_fun_incref(void);
extern "C" void franka_Yr_fun_decref(void);
extern "C" casadi_int franka_Yr_fun_n_in(void);
extern "C" casadi_int franka_Yr_fun_n_out(void);
extern "C" casadi_real franka_Yr_fun_default_in(casadi_int i);
extern "C" const char* franka_Yr_fun_name_in(casadi_int i);
extern "C" const char* franka_Yr_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_Yr_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_Yr_fun_sparsity_out(casadi_int i);
extern "C" int franka_Yr_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_Yr_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_Yr_fun_SZ_ARG 6
#define franka_Yr_fun_SZ_RES 1
#define franka_Yr_fun_SZ_IW 0
#define franka_Yr_fun_SZ_W 0
extern "C" int franka_dyn2reg_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_dyn2reg_fun_checkout(void);
extern "C" void franka_dyn2reg_fun_release(int mem);
extern "C" void franka_dyn2reg_fun_incref(void);
extern "C" void franka_dyn2reg_fun_decref(void);
extern "C" casadi_int franka_dyn2reg_fun_n_in(void);
extern "C" casadi_int franka_dyn2reg_fun_n_out(void);
extern "C" casadi_real franka_dyn2reg_fun_default_in(casadi_int i);
extern "C" const char* franka_dyn2reg_fun_name_in(casadi_int i);
extern "C" const char* franka_dyn2reg_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_dyn2reg_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_dyn2reg_fun_sparsity_out(casadi_int i);
extern "C" int franka_dyn2reg_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_dyn2reg_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_dyn2reg_fun_SZ_ARG 1
#define franka_dyn2reg_fun_SZ_RES 1
#define franka_dyn2reg_fun_SZ_IW 0
#define franka_dyn2reg_fun_SZ_W 0
extern "C" int franka_par_KIN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_par_KIN_fun_checkout(void);
extern "C" void franka_par_KIN_fun_release(int mem);
extern "C" void franka_par_KIN_fun_incref(void);
extern "C" void franka_par_KIN_fun_decref(void);
extern "C" casadi_int franka_par_KIN_fun_n_in(void);
extern "C" casadi_int franka_par_KIN_fun_n_out(void);
extern "C" casadi_real franka_par_KIN_fun_default_in(casadi_int i);
extern "C" const char* franka_par_KIN_fun_name_in(casadi_int i);
extern "C" const char* franka_par_KIN_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_par_KIN_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_par_KIN_fun_sparsity_out(casadi_int i);
extern "C" int franka_par_KIN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_par_KIN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_par_KIN_fun_SZ_ARG 2
#define franka_par_KIN_fun_SZ_RES 1
#define franka_par_KIN_fun_SZ_IW 0
#define franka_par_KIN_fun_SZ_W 0
extern "C" int franka_reg2dyn_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg2dyn_fun_checkout(void);
extern "C" void franka_reg2dyn_fun_release(int mem);
extern "C" void franka_reg2dyn_fun_incref(void);
extern "C" void franka_reg2dyn_fun_decref(void);
extern "C" casadi_int franka_reg2dyn_fun_n_in(void);
extern "C" casadi_int franka_reg2dyn_fun_n_out(void);
extern "C" casadi_real franka_reg2dyn_fun_default_in(casadi_int i);
extern "C" const char* franka_reg2dyn_fun_name_in(casadi_int i);
extern "C" const char* franka_reg2dyn_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg2dyn_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg2dyn_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg2dyn_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg2dyn_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg2dyn_fun_SZ_ARG 1
#define franka_reg2dyn_fun_SZ_RES 1
#define franka_reg2dyn_fun_SZ_IW 0
#define franka_reg2dyn_fun_SZ_W 0
extern "C" int franka_reg_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_C_fun_checkout(void);
extern "C" void franka_reg_C_fun_release(int mem);
extern "C" void franka_reg_C_fun_incref(void);
extern "C" void franka_reg_C_fun_decref(void);
extern "C" casadi_int franka_reg_C_fun_n_in(void);
extern "C" casadi_int franka_reg_C_fun_n_out(void);
extern "C" casadi_real franka_reg_C_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_C_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_C_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_C_fun_SZ_ARG 5
#define franka_reg_C_fun_SZ_RES 1
#define franka_reg_C_fun_SZ_IW 0
#define franka_reg_C_fun_SZ_W 0
extern "C" int franka_reg_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_G_fun_checkout(void);
extern "C" void franka_reg_G_fun_release(int mem);
extern "C" void franka_reg_G_fun_incref(void);
extern "C" void franka_reg_G_fun_decref(void);
extern "C" casadi_int franka_reg_G_fun_n_in(void);
extern "C" casadi_int franka_reg_G_fun_n_out(void);
extern "C" casadi_real franka_reg_G_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_G_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_G_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_G_fun_SZ_ARG 3
#define franka_reg_G_fun_SZ_RES 1
#define franka_reg_G_fun_SZ_IW 0
#define franka_reg_G_fun_SZ_W 0
extern "C" int franka_reg_JTw_EE_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_JTw_EE_fun_checkout(void);
extern "C" void franka_reg_JTw_EE_fun_release(int mem);
extern "C" void franka_reg_JTw_EE_fun_incref(void);
extern "C" void franka_reg_JTw_EE_fun_decref(void);
extern "C" casadi_int franka_reg_JTw_EE_fun_n_in(void);
extern "C" casadi_int franka_reg_JTw_EE_fun_n_out(void);
extern "C" casadi_real franka_reg_JTw_EE_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_JTw_EE_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_JTw_EE_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_JTw_EE_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_JTw_EE_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_JTw_EE_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_JTw_EE_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_JTw_EE_fun_SZ_ARG 4
#define franka_reg_JTw_EE_fun_SZ_RES 1
#define franka_reg_JTw_EE_fun_SZ_IW 0
#define franka_reg_JTw_EE_fun_SZ_W 0
extern "C" int franka_reg_Jdq_EE_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_Jdq_EE_fun_checkout(void);
extern "C" void franka_reg_Jdq_EE_fun_release(int mem);
extern "C" void franka_reg_Jdq_EE_fun_incref(void);
extern "C" void franka_reg_Jdq_EE_fun_decref(void);
extern "C" casadi_int franka_reg_Jdq_EE_fun_n_in(void);
extern "C" casadi_int franka_reg_Jdq_EE_fun_n_out(void);
extern "C" casadi_real franka_reg_Jdq_EE_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_Jdq_EE_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_Jdq_EE_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_Jdq_EE_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_Jdq_EE_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_Jdq_EE_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_Jdq_EE_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_Jdq_EE_fun_SZ_ARG 4
#define franka_reg_Jdq_EE_fun_SZ_RES 1
#define franka_reg_Jdq_EE_fun_SZ_IW 0
#define franka_reg_Jdq_EE_fun_SZ_W 0
extern "C" int franka_reg_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int franka_reg_M_fun_checkout(void);
extern "C" void franka_reg_M_fun_release(int mem);
extern "C" void franka_reg_M_fun_incref(void);
extern "C" void franka_reg_M_fun_decref(void);
extern "C" casadi_int franka_reg_M_fun_n_in(void);
extern "C" casadi_int franka_reg_M_fun_n_out(void);
extern "C" casadi_real franka_reg_M_fun_default_in(casadi_int i);
extern "C" const char* franka_reg_M_fun_name_in(casadi_int i);
extern "C" const char* franka_reg_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* franka_reg_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* franka_reg_M_fun_sparsity_out(casadi_int i);
extern "C" int franka_reg_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int franka_reg_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define franka_reg_M_fun_SZ_ARG 4
#define franka_reg_M_fun_SZ_RES 1
#define franka_reg_M_fun_SZ_IW 0
#define franka_reg_M_fun_SZ_W 0
