/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int C_fun_alloc_mem(void);
extern "C" int C_fun_init_mem(int mem);
extern "C" void C_fun_free_mem(int mem);
extern "C" int C_fun_checkout(void);
extern "C" void C_fun_release(int mem);
extern "C" void C_fun_incref(void);
extern "C" void C_fun_decref(void);
extern "C" casadi_int C_fun_n_in(void);
extern "C" casadi_int C_fun_n_out(void);
extern "C" casadi_real C_fun_default_in(casadi_int i);
extern "C" const char* C_fun_name_in(casadi_int i);
extern "C" const char* C_fun_name_out(casadi_int i);
extern "C" const casadi_int* C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* C_fun_sparsity_out(casadi_int i);
extern "C" int C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define C_fun_SZ_ARG 3
#define C_fun_SZ_RES 1
#define C_fun_SZ_IW 0
#define C_fun_SZ_W 1343
extern "C" int C_std_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int C_std_fun_alloc_mem(void);
extern "C" int C_std_fun_init_mem(int mem);
extern "C" void C_std_fun_free_mem(int mem);
extern "C" int C_std_fun_checkout(void);
extern "C" void C_std_fun_release(int mem);
extern "C" void C_std_fun_incref(void);
extern "C" void C_std_fun_decref(void);
extern "C" casadi_int C_std_fun_n_in(void);
extern "C" casadi_int C_std_fun_n_out(void);
extern "C" casadi_real C_std_fun_default_in(casadi_int i);
extern "C" const char* C_std_fun_name_in(casadi_int i);
extern "C" const char* C_std_fun_name_out(casadi_int i);
extern "C" const casadi_int* C_std_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* C_std_fun_sparsity_out(casadi_int i);
extern "C" int C_std_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int C_std_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define C_std_fun_SZ_ARG 3
#define C_std_fun_SZ_RES 1
#define C_std_fun_SZ_IW 0
#define C_std_fun_SZ_W 471
extern "C" int G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int G_fun_alloc_mem(void);
extern "C" int G_fun_init_mem(int mem);
extern "C" void G_fun_free_mem(int mem);
extern "C" int G_fun_checkout(void);
extern "C" void G_fun_release(int mem);
extern "C" void G_fun_incref(void);
extern "C" void G_fun_decref(void);
extern "C" casadi_int G_fun_n_in(void);
extern "C" casadi_int G_fun_n_out(void);
extern "C" casadi_real G_fun_default_in(casadi_int i);
extern "C" const char* G_fun_name_in(casadi_int i);
extern "C" const char* G_fun_name_out(casadi_int i);
extern "C" const casadi_int* G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* G_fun_sparsity_out(casadi_int i);
extern "C" int G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define G_fun_SZ_ARG 2
#define G_fun_SZ_RES 1
#define G_fun_SZ_IW 0
#define G_fun_SZ_W 54
extern "C" int J_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_0_fun_alloc_mem(void);
extern "C" int J_0_fun_init_mem(int mem);
extern "C" void J_0_fun_free_mem(int mem);
extern "C" int J_0_fun_checkout(void);
extern "C" void J_0_fun_release(int mem);
extern "C" void J_0_fun_incref(void);
extern "C" void J_0_fun_decref(void);
extern "C" casadi_int J_0_fun_n_in(void);
extern "C" casadi_int J_0_fun_n_out(void);
extern "C" casadi_real J_0_fun_default_in(casadi_int i);
extern "C" const char* J_0_fun_name_in(casadi_int i);
extern "C" const char* J_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_0_fun_sparsity_out(casadi_int i);
extern "C" int J_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_0_fun_SZ_ARG 1
#define J_0_fun_SZ_RES 1
#define J_0_fun_SZ_IW 0
#define J_0_fun_SZ_W 2
extern "C" int J_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_1_fun_alloc_mem(void);
extern "C" int J_1_fun_init_mem(int mem);
extern "C" void J_1_fun_free_mem(int mem);
extern "C" int J_1_fun_checkout(void);
extern "C" void J_1_fun_release(int mem);
extern "C" void J_1_fun_incref(void);
extern "C" void J_1_fun_decref(void);
extern "C" casadi_int J_1_fun_n_in(void);
extern "C" casadi_int J_1_fun_n_out(void);
extern "C" casadi_real J_1_fun_default_in(casadi_int i);
extern "C" const char* J_1_fun_name_in(casadi_int i);
extern "C" const char* J_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_1_fun_sparsity_out(casadi_int i);
extern "C" int J_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_1_fun_SZ_ARG 1
#define J_1_fun_SZ_RES 1
#define J_1_fun_SZ_IW 0
#define J_1_fun_SZ_W 3
extern "C" int J_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_2_fun_alloc_mem(void);
extern "C" int J_2_fun_init_mem(int mem);
extern "C" void J_2_fun_free_mem(int mem);
extern "C" int J_2_fun_checkout(void);
extern "C" void J_2_fun_release(int mem);
extern "C" void J_2_fun_incref(void);
extern "C" void J_2_fun_decref(void);
extern "C" casadi_int J_2_fun_n_in(void);
extern "C" casadi_int J_2_fun_n_out(void);
extern "C" casadi_real J_2_fun_default_in(casadi_int i);
extern "C" const char* J_2_fun_name_in(casadi_int i);
extern "C" const char* J_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_2_fun_sparsity_out(casadi_int i);
extern "C" int J_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_2_fun_SZ_ARG 1
#define J_2_fun_SZ_RES 1
#define J_2_fun_SZ_IW 0
#define J_2_fun_SZ_W 12
extern "C" int J_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_3_fun_alloc_mem(void);
extern "C" int J_3_fun_init_mem(int mem);
extern "C" void J_3_fun_free_mem(int mem);
extern "C" int J_3_fun_checkout(void);
extern "C" void J_3_fun_release(int mem);
extern "C" void J_3_fun_incref(void);
extern "C" void J_3_fun_decref(void);
extern "C" casadi_int J_3_fun_n_in(void);
extern "C" casadi_int J_3_fun_n_out(void);
extern "C" casadi_real J_3_fun_default_in(casadi_int i);
extern "C" const char* J_3_fun_name_in(casadi_int i);
extern "C" const char* J_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_3_fun_sparsity_out(casadi_int i);
extern "C" int J_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_3_fun_SZ_ARG 1
#define J_3_fun_SZ_RES 1
#define J_3_fun_SZ_IW 0
#define J_3_fun_SZ_W 22
extern "C" int J_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_4_fun_alloc_mem(void);
extern "C" int J_4_fun_init_mem(int mem);
extern "C" void J_4_fun_free_mem(int mem);
extern "C" int J_4_fun_checkout(void);
extern "C" void J_4_fun_release(int mem);
extern "C" void J_4_fun_incref(void);
extern "C" void J_4_fun_decref(void);
extern "C" casadi_int J_4_fun_n_in(void);
extern "C" casadi_int J_4_fun_n_out(void);
extern "C" casadi_real J_4_fun_default_in(casadi_int i);
extern "C" const char* J_4_fun_name_in(casadi_int i);
extern "C" const char* J_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_4_fun_sparsity_out(casadi_int i);
extern "C" int J_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_4_fun_SZ_ARG 1
#define J_4_fun_SZ_RES 1
#define J_4_fun_SZ_IW 0
#define J_4_fun_SZ_W 34
extern "C" int J_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_5_fun_alloc_mem(void);
extern "C" int J_5_fun_init_mem(int mem);
extern "C" void J_5_fun_free_mem(int mem);
extern "C" int J_5_fun_checkout(void);
extern "C" void J_5_fun_release(int mem);
extern "C" void J_5_fun_incref(void);
extern "C" void J_5_fun_decref(void);
extern "C" casadi_int J_5_fun_n_in(void);
extern "C" casadi_int J_5_fun_n_out(void);
extern "C" casadi_real J_5_fun_default_in(casadi_int i);
extern "C" const char* J_5_fun_name_in(casadi_int i);
extern "C" const char* J_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_5_fun_sparsity_out(casadi_int i);
extern "C" int J_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_5_fun_SZ_ARG 1
#define J_5_fun_SZ_RES 1
#define J_5_fun_SZ_IW 0
#define J_5_fun_SZ_W 36
extern "C" int J_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_6_fun_alloc_mem(void);
extern "C" int J_6_fun_init_mem(int mem);
extern "C" void J_6_fun_free_mem(int mem);
extern "C" int J_6_fun_checkout(void);
extern "C" void J_6_fun_release(int mem);
extern "C" void J_6_fun_incref(void);
extern "C" void J_6_fun_decref(void);
extern "C" casadi_int J_6_fun_n_in(void);
extern "C" casadi_int J_6_fun_n_out(void);
extern "C" casadi_real J_6_fun_default_in(casadi_int i);
extern "C" const char* J_6_fun_name_in(casadi_int i);
extern "C" const char* J_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_6_fun_sparsity_out(casadi_int i);
extern "C" int J_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_6_fun_SZ_ARG 1
#define J_6_fun_SZ_RES 1
#define J_6_fun_SZ_IW 0
#define J_6_fun_SZ_W 51
extern "C" int J_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_7_fun_alloc_mem(void);
extern "C" int J_7_fun_init_mem(int mem);
extern "C" void J_7_fun_free_mem(int mem);
extern "C" int J_7_fun_checkout(void);
extern "C" void J_7_fun_release(int mem);
extern "C" void J_7_fun_incref(void);
extern "C" void J_7_fun_decref(void);
extern "C" casadi_int J_7_fun_n_in(void);
extern "C" casadi_int J_7_fun_n_out(void);
extern "C" casadi_real J_7_fun_default_in(casadi_int i);
extern "C" const char* J_7_fun_name_in(casadi_int i);
extern "C" const char* J_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_7_fun_sparsity_out(casadi_int i);
extern "C" int J_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_7_fun_SZ_ARG 1
#define J_7_fun_SZ_RES 1
#define J_7_fun_SZ_IW 0
#define J_7_fun_SZ_W 51
extern "C" int J_cm_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_0_fun_alloc_mem(void);
extern "C" int J_cm_0_fun_init_mem(int mem);
extern "C" void J_cm_0_fun_free_mem(int mem);
extern "C" int J_cm_0_fun_checkout(void);
extern "C" void J_cm_0_fun_release(int mem);
extern "C" void J_cm_0_fun_incref(void);
extern "C" void J_cm_0_fun_decref(void);
extern "C" casadi_int J_cm_0_fun_n_in(void);
extern "C" casadi_int J_cm_0_fun_n_out(void);
extern "C" casadi_real J_cm_0_fun_default_in(casadi_int i);
extern "C" const char* J_cm_0_fun_name_in(casadi_int i);
extern "C" const char* J_cm_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_0_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_0_fun_SZ_ARG 2
#define J_cm_0_fun_SZ_RES 1
#define J_cm_0_fun_SZ_IW 0
#define J_cm_0_fun_SZ_W 6
extern "C" int J_cm_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_1_fun_alloc_mem(void);
extern "C" int J_cm_1_fun_init_mem(int mem);
extern "C" void J_cm_1_fun_free_mem(int mem);
extern "C" int J_cm_1_fun_checkout(void);
extern "C" void J_cm_1_fun_release(int mem);
extern "C" void J_cm_1_fun_incref(void);
extern "C" void J_cm_1_fun_decref(void);
extern "C" casadi_int J_cm_1_fun_n_in(void);
extern "C" casadi_int J_cm_1_fun_n_out(void);
extern "C" casadi_real J_cm_1_fun_default_in(casadi_int i);
extern "C" const char* J_cm_1_fun_name_in(casadi_int i);
extern "C" const char* J_cm_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_1_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_1_fun_SZ_ARG 2
#define J_cm_1_fun_SZ_RES 1
#define J_cm_1_fun_SZ_IW 0
#define J_cm_1_fun_SZ_W 12
extern "C" int J_cm_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_2_fun_alloc_mem(void);
extern "C" int J_cm_2_fun_init_mem(int mem);
extern "C" void J_cm_2_fun_free_mem(int mem);
extern "C" int J_cm_2_fun_checkout(void);
extern "C" void J_cm_2_fun_release(int mem);
extern "C" void J_cm_2_fun_incref(void);
extern "C" void J_cm_2_fun_decref(void);
extern "C" casadi_int J_cm_2_fun_n_in(void);
extern "C" casadi_int J_cm_2_fun_n_out(void);
extern "C" casadi_real J_cm_2_fun_default_in(casadi_int i);
extern "C" const char* J_cm_2_fun_name_in(casadi_int i);
extern "C" const char* J_cm_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_2_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_2_fun_SZ_ARG 2
#define J_cm_2_fun_SZ_RES 1
#define J_cm_2_fun_SZ_IW 0
#define J_cm_2_fun_SZ_W 24
extern "C" int J_cm_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_3_fun_alloc_mem(void);
extern "C" int J_cm_3_fun_init_mem(int mem);
extern "C" void J_cm_3_fun_free_mem(int mem);
extern "C" int J_cm_3_fun_checkout(void);
extern "C" void J_cm_3_fun_release(int mem);
extern "C" void J_cm_3_fun_incref(void);
extern "C" void J_cm_3_fun_decref(void);
extern "C" casadi_int J_cm_3_fun_n_in(void);
extern "C" casadi_int J_cm_3_fun_n_out(void);
extern "C" casadi_real J_cm_3_fun_default_in(casadi_int i);
extern "C" const char* J_cm_3_fun_name_in(casadi_int i);
extern "C" const char* J_cm_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_3_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_3_fun_SZ_ARG 2
#define J_cm_3_fun_SZ_RES 1
#define J_cm_3_fun_SZ_IW 0
#define J_cm_3_fun_SZ_W 32
extern "C" int J_cm_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_4_fun_alloc_mem(void);
extern "C" int J_cm_4_fun_init_mem(int mem);
extern "C" void J_cm_4_fun_free_mem(int mem);
extern "C" int J_cm_4_fun_checkout(void);
extern "C" void J_cm_4_fun_release(int mem);
extern "C" void J_cm_4_fun_incref(void);
extern "C" void J_cm_4_fun_decref(void);
extern "C" casadi_int J_cm_4_fun_n_in(void);
extern "C" casadi_int J_cm_4_fun_n_out(void);
extern "C" casadi_real J_cm_4_fun_default_in(casadi_int i);
extern "C" const char* J_cm_4_fun_name_in(casadi_int i);
extern "C" const char* J_cm_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_4_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_4_fun_SZ_ARG 2
#define J_cm_4_fun_SZ_RES 1
#define J_cm_4_fun_SZ_IW 0
#define J_cm_4_fun_SZ_W 43
extern "C" int J_cm_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_5_fun_alloc_mem(void);
extern "C" int J_cm_5_fun_init_mem(int mem);
extern "C" void J_cm_5_fun_free_mem(int mem);
extern "C" int J_cm_5_fun_checkout(void);
extern "C" void J_cm_5_fun_release(int mem);
extern "C" void J_cm_5_fun_incref(void);
extern "C" void J_cm_5_fun_decref(void);
extern "C" casadi_int J_cm_5_fun_n_in(void);
extern "C" casadi_int J_cm_5_fun_n_out(void);
extern "C" casadi_real J_cm_5_fun_default_in(casadi_int i);
extern "C" const char* J_cm_5_fun_name_in(casadi_int i);
extern "C" const char* J_cm_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_5_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_5_fun_SZ_ARG 2
#define J_cm_5_fun_SZ_RES 1
#define J_cm_5_fun_SZ_IW 0
#define J_cm_5_fun_SZ_W 49
extern "C" int J_cm_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_cm_6_fun_alloc_mem(void);
extern "C" int J_cm_6_fun_init_mem(int mem);
extern "C" void J_cm_6_fun_free_mem(int mem);
extern "C" int J_cm_6_fun_checkout(void);
extern "C" void J_cm_6_fun_release(int mem);
extern "C" void J_cm_6_fun_incref(void);
extern "C" void J_cm_6_fun_decref(void);
extern "C" casadi_int J_cm_6_fun_n_in(void);
extern "C" casadi_int J_cm_6_fun_n_out(void);
extern "C" casadi_real J_cm_6_fun_default_in(casadi_int i);
extern "C" const char* J_cm_6_fun_name_in(casadi_int i);
extern "C" const char* J_cm_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_cm_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_cm_6_fun_sparsity_out(casadi_int i);
extern "C" int J_cm_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_cm_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_cm_6_fun_SZ_ARG 2
#define J_cm_6_fun_SZ_RES 1
#define J_cm_6_fun_SZ_IW 0
#define J_cm_6_fun_SZ_W 59
extern "C" int J_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_ee_fun_alloc_mem(void);
extern "C" int J_ee_fun_init_mem(int mem);
extern "C" void J_ee_fun_free_mem(int mem);
extern "C" int J_ee_fun_checkout(void);
extern "C" void J_ee_fun_release(int mem);
extern "C" void J_ee_fun_incref(void);
extern "C" void J_ee_fun_decref(void);
extern "C" casadi_int J_ee_fun_n_in(void);
extern "C" casadi_int J_ee_fun_n_out(void);
extern "C" casadi_real J_ee_fun_default_in(casadi_int i);
extern "C" const char* J_ee_fun_name_in(casadi_int i);
extern "C" const char* J_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_ee_fun_sparsity_out(casadi_int i);
extern "C" int J_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_ee_fun_SZ_ARG 1
#define J_ee_fun_SZ_RES 1
#define J_ee_fun_SZ_IW 0
#define J_ee_fun_SZ_W 51
extern "C" int J_ee_dot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_ee_dot_fun_alloc_mem(void);
extern "C" int J_ee_dot_fun_init_mem(int mem);
extern "C" void J_ee_dot_fun_free_mem(int mem);
extern "C" int J_ee_dot_fun_checkout(void);
extern "C" void J_ee_dot_fun_release(int mem);
extern "C" void J_ee_dot_fun_incref(void);
extern "C" void J_ee_dot_fun_decref(void);
extern "C" casadi_int J_ee_dot_fun_n_in(void);
extern "C" casadi_int J_ee_dot_fun_n_out(void);
extern "C" casadi_real J_ee_dot_fun_default_in(casadi_int i);
extern "C" const char* J_ee_dot_fun_name_in(casadi_int i);
extern "C" const char* J_ee_dot_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_ee_dot_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_ee_dot_fun_sparsity_out(casadi_int i);
extern "C" int J_ee_dot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_ee_dot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_ee_dot_fun_SZ_ARG 2
#define J_ee_dot_fun_SZ_RES 1
#define J_ee_dot_fun_SZ_IW 0
#define J_ee_dot_fun_SZ_W 91
extern "C" int J_ee_pinv_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int J_ee_pinv_fun_alloc_mem(void);
extern "C" int J_ee_pinv_fun_init_mem(int mem);
extern "C" void J_ee_pinv_fun_free_mem(int mem);
extern "C" int J_ee_pinv_fun_checkout(void);
extern "C" void J_ee_pinv_fun_release(int mem);
extern "C" void J_ee_pinv_fun_incref(void);
extern "C" void J_ee_pinv_fun_decref(void);
extern "C" casadi_int J_ee_pinv_fun_n_in(void);
extern "C" casadi_int J_ee_pinv_fun_n_out(void);
extern "C" casadi_real J_ee_pinv_fun_default_in(casadi_int i);
extern "C" const char* J_ee_pinv_fun_name_in(casadi_int i);
extern "C" const char* J_ee_pinv_fun_name_out(casadi_int i);
extern "C" const casadi_int* J_ee_pinv_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* J_ee_pinv_fun_sparsity_out(casadi_int i);
extern "C" int J_ee_pinv_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int J_ee_pinv_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_ee_pinv_fun_SZ_ARG 1
#define J_ee_pinv_fun_SZ_RES 1
#define J_ee_pinv_fun_SZ_IW 0
#define J_ee_pinv_fun_SZ_W 94
extern "C" int M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int M_fun_alloc_mem(void);
extern "C" int M_fun_init_mem(int mem);
extern "C" void M_fun_free_mem(int mem);
extern "C" int M_fun_checkout(void);
extern "C" void M_fun_release(int mem);
extern "C" void M_fun_incref(void);
extern "C" void M_fun_decref(void);
extern "C" casadi_int M_fun_n_in(void);
extern "C" casadi_int M_fun_n_out(void);
extern "C" casadi_real M_fun_default_in(casadi_int i);
extern "C" const char* M_fun_name_in(casadi_int i);
extern "C" const char* M_fun_name_out(casadi_int i);
extern "C" const casadi_int* M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* M_fun_sparsity_out(casadi_int i);
extern "C" int M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define M_fun_SZ_ARG 2
#define M_fun_SZ_RES 1
#define M_fun_SZ_IW 0
#define M_fun_SZ_W 247
extern "C" int T_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_fun_alloc_mem(void);
extern "C" int T_0_fun_init_mem(int mem);
extern "C" void T_0_fun_free_mem(int mem);
extern "C" int T_0_fun_checkout(void);
extern "C" void T_0_fun_release(int mem);
extern "C" void T_0_fun_incref(void);
extern "C" void T_0_fun_decref(void);
extern "C" casadi_int T_0_fun_n_in(void);
extern "C" casadi_int T_0_fun_n_out(void);
extern "C" casadi_real T_0_fun_default_in(casadi_int i);
extern "C" const char* T_0_fun_name_in(casadi_int i);
extern "C" const char* T_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_fun_sparsity_out(casadi_int i);
extern "C" int T_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_fun_SZ_ARG 1
#define T_0_fun_SZ_RES 1
#define T_0_fun_SZ_IW 0
#define T_0_fun_SZ_W 3
extern "C" int T_0_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_0_fun_alloc_mem(void);
extern "C" int T_0_0_fun_init_mem(int mem);
extern "C" void T_0_0_fun_free_mem(int mem);
extern "C" int T_0_0_fun_checkout(void);
extern "C" void T_0_0_fun_release(int mem);
extern "C" void T_0_0_fun_incref(void);
extern "C" void T_0_0_fun_decref(void);
extern "C" casadi_int T_0_0_fun_n_in(void);
extern "C" casadi_int T_0_0_fun_n_out(void);
extern "C" casadi_real T_0_0_fun_default_in(casadi_int i);
extern "C" const char* T_0_0_fun_name_in(casadi_int i);
extern "C" const char* T_0_0_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_0_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_0_fun_sparsity_out(casadi_int i);
extern "C" int T_0_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_0_fun_SZ_ARG 1
#define T_0_0_fun_SZ_RES 1
#define T_0_0_fun_SZ_IW 0
#define T_0_0_fun_SZ_W 3
extern "C" int T_0_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_1_fun_alloc_mem(void);
extern "C" int T_0_1_fun_init_mem(int mem);
extern "C" void T_0_1_fun_free_mem(int mem);
extern "C" int T_0_1_fun_checkout(void);
extern "C" void T_0_1_fun_release(int mem);
extern "C" void T_0_1_fun_incref(void);
extern "C" void T_0_1_fun_decref(void);
extern "C" casadi_int T_0_1_fun_n_in(void);
extern "C" casadi_int T_0_1_fun_n_out(void);
extern "C" casadi_real T_0_1_fun_default_in(casadi_int i);
extern "C" const char* T_0_1_fun_name_in(casadi_int i);
extern "C" const char* T_0_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_1_fun_sparsity_out(casadi_int i);
extern "C" int T_0_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_1_fun_SZ_ARG 1
#define T_0_1_fun_SZ_RES 1
#define T_0_1_fun_SZ_IW 0
#define T_0_1_fun_SZ_W 9
extern "C" int T_0_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_2_fun_alloc_mem(void);
extern "C" int T_0_2_fun_init_mem(int mem);
extern "C" void T_0_2_fun_free_mem(int mem);
extern "C" int T_0_2_fun_checkout(void);
extern "C" void T_0_2_fun_release(int mem);
extern "C" void T_0_2_fun_incref(void);
extern "C" void T_0_2_fun_decref(void);
extern "C" casadi_int T_0_2_fun_n_in(void);
extern "C" casadi_int T_0_2_fun_n_out(void);
extern "C" casadi_real T_0_2_fun_default_in(casadi_int i);
extern "C" const char* T_0_2_fun_name_in(casadi_int i);
extern "C" const char* T_0_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_2_fun_sparsity_out(casadi_int i);
extern "C" int T_0_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_2_fun_SZ_ARG 1
#define T_0_2_fun_SZ_RES 1
#define T_0_2_fun_SZ_IW 0
#define T_0_2_fun_SZ_W 14
extern "C" int T_0_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_3_fun_alloc_mem(void);
extern "C" int T_0_3_fun_init_mem(int mem);
extern "C" void T_0_3_fun_free_mem(int mem);
extern "C" int T_0_3_fun_checkout(void);
extern "C" void T_0_3_fun_release(int mem);
extern "C" void T_0_3_fun_incref(void);
extern "C" void T_0_3_fun_decref(void);
extern "C" casadi_int T_0_3_fun_n_in(void);
extern "C" casadi_int T_0_3_fun_n_out(void);
extern "C" casadi_real T_0_3_fun_default_in(casadi_int i);
extern "C" const char* T_0_3_fun_name_in(casadi_int i);
extern "C" const char* T_0_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_3_fun_sparsity_out(casadi_int i);
extern "C" int T_0_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_3_fun_SZ_ARG 1
#define T_0_3_fun_SZ_RES 1
#define T_0_3_fun_SZ_IW 0
#define T_0_3_fun_SZ_W 22
extern "C" int T_0_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_4_fun_alloc_mem(void);
extern "C" int T_0_4_fun_init_mem(int mem);
extern "C" void T_0_4_fun_free_mem(int mem);
extern "C" int T_0_4_fun_checkout(void);
extern "C" void T_0_4_fun_release(int mem);
extern "C" void T_0_4_fun_incref(void);
extern "C" void T_0_4_fun_decref(void);
extern "C" casadi_int T_0_4_fun_n_in(void);
extern "C" casadi_int T_0_4_fun_n_out(void);
extern "C" casadi_real T_0_4_fun_default_in(casadi_int i);
extern "C" const char* T_0_4_fun_name_in(casadi_int i);
extern "C" const char* T_0_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_4_fun_sparsity_out(casadi_int i);
extern "C" int T_0_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_4_fun_SZ_ARG 1
#define T_0_4_fun_SZ_RES 1
#define T_0_4_fun_SZ_IW 0
#define T_0_4_fun_SZ_W 29
extern "C" int T_0_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_5_fun_alloc_mem(void);
extern "C" int T_0_5_fun_init_mem(int mem);
extern "C" void T_0_5_fun_free_mem(int mem);
extern "C" int T_0_5_fun_checkout(void);
extern "C" void T_0_5_fun_release(int mem);
extern "C" void T_0_5_fun_incref(void);
extern "C" void T_0_5_fun_decref(void);
extern "C" casadi_int T_0_5_fun_n_in(void);
extern "C" casadi_int T_0_5_fun_n_out(void);
extern "C" casadi_real T_0_5_fun_default_in(casadi_int i);
extern "C" const char* T_0_5_fun_name_in(casadi_int i);
extern "C" const char* T_0_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_5_fun_sparsity_out(casadi_int i);
extern "C" int T_0_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_5_fun_SZ_ARG 1
#define T_0_5_fun_SZ_RES 1
#define T_0_5_fun_SZ_IW 0
#define T_0_5_fun_SZ_W 38
extern "C" int T_0_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_6_fun_alloc_mem(void);
extern "C" int T_0_6_fun_init_mem(int mem);
extern "C" void T_0_6_fun_free_mem(int mem);
extern "C" int T_0_6_fun_checkout(void);
extern "C" void T_0_6_fun_release(int mem);
extern "C" void T_0_6_fun_incref(void);
extern "C" void T_0_6_fun_decref(void);
extern "C" casadi_int T_0_6_fun_n_in(void);
extern "C" casadi_int T_0_6_fun_n_out(void);
extern "C" casadi_real T_0_6_fun_default_in(casadi_int i);
extern "C" const char* T_0_6_fun_name_in(casadi_int i);
extern "C" const char* T_0_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_6_fun_sparsity_out(casadi_int i);
extern "C" int T_0_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_6_fun_SZ_ARG 1
#define T_0_6_fun_SZ_RES 1
#define T_0_6_fun_SZ_IW 0
#define T_0_6_fun_SZ_W 43
extern "C" int T_0_7_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_7_fun_alloc_mem(void);
extern "C" int T_0_7_fun_init_mem(int mem);
extern "C" void T_0_7_fun_free_mem(int mem);
extern "C" int T_0_7_fun_checkout(void);
extern "C" void T_0_7_fun_release(int mem);
extern "C" void T_0_7_fun_incref(void);
extern "C" void T_0_7_fun_decref(void);
extern "C" casadi_int T_0_7_fun_n_in(void);
extern "C" casadi_int T_0_7_fun_n_out(void);
extern "C" casadi_real T_0_7_fun_default_in(casadi_int i);
extern "C" const char* T_0_7_fun_name_in(casadi_int i);
extern "C" const char* T_0_7_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_7_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_7_fun_sparsity_out(casadi_int i);
extern "C" int T_0_7_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_7_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_7_fun_SZ_ARG 1
#define T_0_7_fun_SZ_RES 1
#define T_0_7_fun_SZ_IW 0
#define T_0_7_fun_SZ_W 43
extern "C" int T_0_ee_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_0_ee_fun_alloc_mem(void);
extern "C" int T_0_ee_fun_init_mem(int mem);
extern "C" void T_0_ee_fun_free_mem(int mem);
extern "C" int T_0_ee_fun_checkout(void);
extern "C" void T_0_ee_fun_release(int mem);
extern "C" void T_0_ee_fun_incref(void);
extern "C" void T_0_ee_fun_decref(void);
extern "C" casadi_int T_0_ee_fun_n_in(void);
extern "C" casadi_int T_0_ee_fun_n_out(void);
extern "C" casadi_real T_0_ee_fun_default_in(casadi_int i);
extern "C" const char* T_0_ee_fun_name_in(casadi_int i);
extern "C" const char* T_0_ee_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_0_ee_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_0_ee_fun_sparsity_out(casadi_int i);
extern "C" int T_0_ee_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_0_ee_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_0_ee_fun_SZ_ARG 1
#define T_0_ee_fun_SZ_RES 1
#define T_0_ee_fun_SZ_IW 0
#define T_0_ee_fun_SZ_W 43
extern "C" int T_1_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_1_fun_alloc_mem(void);
extern "C" int T_1_fun_init_mem(int mem);
extern "C" void T_1_fun_free_mem(int mem);
extern "C" int T_1_fun_checkout(void);
extern "C" void T_1_fun_release(int mem);
extern "C" void T_1_fun_incref(void);
extern "C" void T_1_fun_decref(void);
extern "C" casadi_int T_1_fun_n_in(void);
extern "C" casadi_int T_1_fun_n_out(void);
extern "C" casadi_real T_1_fun_default_in(casadi_int i);
extern "C" const char* T_1_fun_name_in(casadi_int i);
extern "C" const char* T_1_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_1_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_1_fun_sparsity_out(casadi_int i);
extern "C" int T_1_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_1_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_1_fun_SZ_ARG 1
#define T_1_fun_SZ_RES 1
#define T_1_fun_SZ_IW 0
#define T_1_fun_SZ_W 4
extern "C" int T_2_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_2_fun_alloc_mem(void);
extern "C" int T_2_fun_init_mem(int mem);
extern "C" void T_2_fun_free_mem(int mem);
extern "C" int T_2_fun_checkout(void);
extern "C" void T_2_fun_release(int mem);
extern "C" void T_2_fun_incref(void);
extern "C" void T_2_fun_decref(void);
extern "C" casadi_int T_2_fun_n_in(void);
extern "C" casadi_int T_2_fun_n_out(void);
extern "C" casadi_real T_2_fun_default_in(casadi_int i);
extern "C" const char* T_2_fun_name_in(casadi_int i);
extern "C" const char* T_2_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_2_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_2_fun_sparsity_out(casadi_int i);
extern "C" int T_2_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_2_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_2_fun_SZ_ARG 1
#define T_2_fun_SZ_RES 1
#define T_2_fun_SZ_IW 0
#define T_2_fun_SZ_W 4
extern "C" int T_3_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_3_fun_alloc_mem(void);
extern "C" int T_3_fun_init_mem(int mem);
extern "C" void T_3_fun_free_mem(int mem);
extern "C" int T_3_fun_checkout(void);
extern "C" void T_3_fun_release(int mem);
extern "C" void T_3_fun_incref(void);
extern "C" void T_3_fun_decref(void);
extern "C" casadi_int T_3_fun_n_in(void);
extern "C" casadi_int T_3_fun_n_out(void);
extern "C" casadi_real T_3_fun_default_in(casadi_int i);
extern "C" const char* T_3_fun_name_in(casadi_int i);
extern "C" const char* T_3_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_3_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_3_fun_sparsity_out(casadi_int i);
extern "C" int T_3_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_3_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_3_fun_SZ_ARG 1
#define T_3_fun_SZ_RES 1
#define T_3_fun_SZ_IW 0
#define T_3_fun_SZ_W 4
extern "C" int T_4_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_4_fun_alloc_mem(void);
extern "C" int T_4_fun_init_mem(int mem);
extern "C" void T_4_fun_free_mem(int mem);
extern "C" int T_4_fun_checkout(void);
extern "C" void T_4_fun_release(int mem);
extern "C" void T_4_fun_incref(void);
extern "C" void T_4_fun_decref(void);
extern "C" casadi_int T_4_fun_n_in(void);
extern "C" casadi_int T_4_fun_n_out(void);
extern "C" casadi_real T_4_fun_default_in(casadi_int i);
extern "C" const char* T_4_fun_name_in(casadi_int i);
extern "C" const char* T_4_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_4_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_4_fun_sparsity_out(casadi_int i);
extern "C" int T_4_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_4_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_4_fun_SZ_ARG 1
#define T_4_fun_SZ_RES 1
#define T_4_fun_SZ_IW 0
#define T_4_fun_SZ_W 4
extern "C" int T_5_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_5_fun_alloc_mem(void);
extern "C" int T_5_fun_init_mem(int mem);
extern "C" void T_5_fun_free_mem(int mem);
extern "C" int T_5_fun_checkout(void);
extern "C" void T_5_fun_release(int mem);
extern "C" void T_5_fun_incref(void);
extern "C" void T_5_fun_decref(void);
extern "C" casadi_int T_5_fun_n_in(void);
extern "C" casadi_int T_5_fun_n_out(void);
extern "C" casadi_real T_5_fun_default_in(casadi_int i);
extern "C" const char* T_5_fun_name_in(casadi_int i);
extern "C" const char* T_5_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_5_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_5_fun_sparsity_out(casadi_int i);
extern "C" int T_5_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_5_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_5_fun_SZ_ARG 1
#define T_5_fun_SZ_RES 1
#define T_5_fun_SZ_IW 0
#define T_5_fun_SZ_W 4
extern "C" int T_6_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int T_6_fun_alloc_mem(void);
extern "C" int T_6_fun_init_mem(int mem);
extern "C" void T_6_fun_free_mem(int mem);
extern "C" int T_6_fun_checkout(void);
extern "C" void T_6_fun_release(int mem);
extern "C" void T_6_fun_incref(void);
extern "C" void T_6_fun_decref(void);
extern "C" casadi_int T_6_fun_n_in(void);
extern "C" casadi_int T_6_fun_n_out(void);
extern "C" casadi_real T_6_fun_default_in(casadi_int i);
extern "C" const char* T_6_fun_name_in(casadi_int i);
extern "C" const char* T_6_fun_name_out(casadi_int i);
extern "C" const casadi_int* T_6_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* T_6_fun_sparsity_out(casadi_int i);
extern "C" int T_6_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int T_6_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define T_6_fun_SZ_ARG 1
#define T_6_fun_SZ_RES 1
#define T_6_fun_SZ_IW 0
#define T_6_fun_SZ_W 4
extern "C" int Yr_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int Yr_fun_alloc_mem(void);
extern "C" int Yr_fun_init_mem(int mem);
extern "C" void Yr_fun_free_mem(int mem);
extern "C" int Yr_fun_checkout(void);
extern "C" void Yr_fun_release(int mem);
extern "C" void Yr_fun_incref(void);
extern "C" void Yr_fun_decref(void);
extern "C" casadi_int Yr_fun_n_in(void);
extern "C" casadi_int Yr_fun_n_out(void);
extern "C" casadi_real Yr_fun_default_in(casadi_int i);
extern "C" const char* Yr_fun_name_in(casadi_int i);
extern "C" const char* Yr_fun_name_out(casadi_int i);
extern "C" const casadi_int* Yr_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* Yr_fun_sparsity_out(casadi_int i);
extern "C" int Yr_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int Yr_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Yr_fun_SZ_ARG 4
#define Yr_fun_SZ_RES 1
#define Yr_fun_SZ_IW 0
#define Yr_fun_SZ_W 475
extern "C" int reg_C_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int reg_C_fun_alloc_mem(void);
extern "C" int reg_C_fun_init_mem(int mem);
extern "C" void reg_C_fun_free_mem(int mem);
extern "C" int reg_C_fun_checkout(void);
extern "C" void reg_C_fun_release(int mem);
extern "C" void reg_C_fun_incref(void);
extern "C" void reg_C_fun_decref(void);
extern "C" casadi_int reg_C_fun_n_in(void);
extern "C" casadi_int reg_C_fun_n_out(void);
extern "C" casadi_real reg_C_fun_default_in(casadi_int i);
extern "C" const char* reg_C_fun_name_in(casadi_int i);
extern "C" const char* reg_C_fun_name_out(casadi_int i);
extern "C" const casadi_int* reg_C_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* reg_C_fun_sparsity_out(casadi_int i);
extern "C" int reg_C_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int reg_C_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define reg_C_fun_SZ_ARG 3
#define reg_C_fun_SZ_RES 1
#define reg_C_fun_SZ_IW 0
#define reg_C_fun_SZ_W 450
extern "C" int reg_G_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int reg_G_fun_alloc_mem(void);
extern "C" int reg_G_fun_init_mem(int mem);
extern "C" void reg_G_fun_free_mem(int mem);
extern "C" int reg_G_fun_checkout(void);
extern "C" void reg_G_fun_release(int mem);
extern "C" void reg_G_fun_incref(void);
extern "C" void reg_G_fun_decref(void);
extern "C" casadi_int reg_G_fun_n_in(void);
extern "C" casadi_int reg_G_fun_n_out(void);
extern "C" casadi_real reg_G_fun_default_in(casadi_int i);
extern "C" const char* reg_G_fun_name_in(casadi_int i);
extern "C" const char* reg_G_fun_name_out(casadi_int i);
extern "C" const casadi_int* reg_G_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* reg_G_fun_sparsity_out(casadi_int i);
extern "C" int reg_G_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int reg_G_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define reg_G_fun_SZ_ARG 1
#define reg_G_fun_SZ_RES 1
#define reg_G_fun_SZ_IW 0
#define reg_G_fun_SZ_W 65
extern "C" int reg_M_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int reg_M_fun_alloc_mem(void);
extern "C" int reg_M_fun_init_mem(int mem);
extern "C" void reg_M_fun_free_mem(int mem);
extern "C" int reg_M_fun_checkout(void);
extern "C" void reg_M_fun_release(int mem);
extern "C" void reg_M_fun_incref(void);
extern "C" void reg_M_fun_decref(void);
extern "C" casadi_int reg_M_fun_n_in(void);
extern "C" casadi_int reg_M_fun_n_out(void);
extern "C" casadi_real reg_M_fun_default_in(casadi_int i);
extern "C" const char* reg_M_fun_name_in(casadi_int i);
extern "C" const char* reg_M_fun_name_out(casadi_int i);
extern "C" const casadi_int* reg_M_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* reg_M_fun_sparsity_out(casadi_int i);
extern "C" int reg_M_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int reg_M_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define reg_M_fun_SZ_ARG 2
#define reg_M_fun_SZ_RES 1
#define reg_M_fun_SZ_IW 0
#define reg_M_fun_SZ_W 63
