#ifndef THUNDER_franka_H
#define THUNDER_franka_H

#include <iostream>
#include <string>
#include <cmath>
#include <eigen3/Eigen/Dense>
#include <yaml-cpp/yaml.h>
#include <fstream>

using std::string;
using std::vector;
using std::map;
using Eigen::MatrixXd;
using Eigen::VectorXd;
using Eigen::Matrix;
using Eigen::Vector;


// ------------------- //
// --- ROBOT CLASS --- //
// ------------------- //

// Contains all the properties, parameters, and functions generated by CadADi
class thunder_franka{
	private:

		// ------------------ //
		// --- Parameters --- //
		// ------------------ //

		// Kinematic frame in xyzrpy
		Vector<double, 6> KIN_EE_xyzrpy = {0, 0, 0, 0, 0, 0};
		// Kinematic frame in xyzrpy
		Matrix<double,6,1> KIN_base_xyzrpy;
		// Jerk
		Matrix<double,7,1> d3q;
		// Snap
		Matrix<double,7,1> d4q;
		// Acceleration
		Matrix<double,7,1> ddq;
		// Acceleration reference
		Matrix<double,7,1> ddqr;
		// Velocity
		Matrix<double,7,1> dq;
		// Velocity reference
		Matrix<double,7,1> dqr;
		// Dynamic parameters
		Matrix<double,10,1> par_DYN;
		// Dynamic parameters for regressor
		Matrix<double,90,1> par_REG;
		// Configuration
		Matrix<double,7,1> q;
		// Wrench
		Matrix<double,6,1> w;


	public:

		// ------------------ //
		// --- Properties --- //
		// ------------------ //

		// Robot name
		const string robotName = "franka";

		// Order of the link friction model
		const int Dl_order = 0;
		// Standard number of dynamic parameters per link
		const int STD_PAR_LINK = 10;
		// Joints that are available in the generated library
		const vector<bool> jointsAvailable = {false, false, false, false, false, false, false, false, true};
		// Axes of joints
		const vector<vector<double>> jointsAxis = {{0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}, {0, 0, 1}};
		// Create jacobian derivatives for these joints
		const vector<bool> jointsDerivatives = {false, false, false, false, false, false, false, false, true};
		// Degrees of freedom of each joint
		const vector<int> jointsDimension = {0, 1, 1, 1, 1, 1, 1, 1, 0};
		// Name of joints
		const vector<string> jointsName = {"base", "link0", "link1", "link2", "link3", "link4", "link5", "link6", "EE"};
		// Parent Id of joints
		const vector<int> jointsParent = {-1, 0, 1, 2, 3, 4, 5, 6, 7};
		// Type of joints
		const vector<string> jointsType = {"FIXED", "R", "R", "R", "R", "R", "R", "R", "FIXED"};
		// Number of degrees of freedom
		const int ndof = 7;
		// Number of joints
		const int numJoints = 9;


		// ----------------- //
		// --- Functions --- //
		// ----------------- //

		// Default constructor
		thunder_franka();

		// get the parameter: KIN_EE_xyzrpy
		Matrix<double,6,1> get_KIN_EE_xyzrpy();
		// get the parameter: KIN_base_xyzrpy
		Matrix<double,6,1> get_KIN_base_xyzrpy();
		// get the parameter: d3q
		Matrix<double,7,1> get_d3q();
		// get the parameter: d4q
		Matrix<double,7,1> get_d4q();
		// get the parameter: ddq
		Matrix<double,7,1> get_ddq();
		// get the parameter: ddqr
		Matrix<double,7,1> get_ddqr();
		// get the parameter: dq
		Matrix<double,7,1> get_dq();
		// get the parameter: dqr
		Matrix<double,7,1> get_dqr();
		// get the parameter: par_DYN
		Matrix<double,10,1> get_par_DYN();
		// get the parameter: par_REG
		Matrix<double,90,1> get_par_REG();
		// get the parameter: q
		Matrix<double,7,1> get_q();
		// get the parameter: w
		Matrix<double,6,1> get_w();
		// set the parameter: KIN_EE_xyzrpy
		void set_KIN_EE_xyzrpy(Matrix<double,6,1> value);
		// set the parameter: KIN_base_xyzrpy
		void set_KIN_base_xyzrpy(Matrix<double,6,1> value);
		// set the parameter: d3q
		void set_d3q(Matrix<double,7,1> value);
		// set the parameter: d4q
		void set_d4q(Matrix<double,7,1> value);
		// set the parameter: ddq
		void set_ddq(Matrix<double,7,1> value);
		// set the parameter: ddqr
		void set_ddqr(Matrix<double,7,1> value);
		// set the parameter: dq
		void set_dq(Matrix<double,7,1> value);
		// set the parameter: dqr
		void set_dqr(Matrix<double,7,1> value);
		// set the parameter: par_DYN
		void set_par_DYN(Matrix<double,10,1> value);
		// set the parameter: par_REG
		void set_par_REG(Matrix<double,90,1> value);
		// set the parameter: q
		void set_q(Matrix<double,7,1> value);
		// set the parameter: w
		void set_w(Matrix<double,6,1> value);

		/**
		 * @brief Save parameters to file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to save ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int save_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Load parameters from file
		 * 
		 * @param  par_file:  parameter file
		 * 
		 * @param  par_list={}:  list of parameters to load ({} means all parameters)
		 * 
		 * @return  1: succeed,  0: failed
		 */ 
		int load_par(string par_file, vector<string> par_list = {});

		/**
		 * @brief Manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C();

		/**
		 * @brief Second time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, d3q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_ddot();

		/**
		 * @brief Time derivative of the Coriolis matrix
		 * 
		 * - depends on: {q, dq, ddq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_dot();

		/**
		 * @brief Classic formulation of the manipulator Coriolis matrix
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_C_std();

		/**
		 * @brief Manipulator gravity terms
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G();

		/**
		 * @brief Second time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, ddq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G_ddot();

		/**
		 * @brief Time derivative of the gravity vector
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,1> get_G_dot();

		/**
		 * @brief Jacobian of frame 0
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_0();

		/**
		 * @brief Jacobian of frame 1
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_1();

		/**
		 * @brief Jacobian of frame 2
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_2();

		/**
		 * @brief Jacobian of frame 3
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_3();

		/**
		 * @brief Jacobian of frame 4
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_4();

		/**
		 * @brief Jacobian of frame 5
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_5();

		/**
		 * @brief Jacobian of frame 6
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_6();

		/**
		 * @brief Jacobian of frame 7
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_7();

		/**
		 * @brief Jacobian of frame 8
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_8();

		/**
		 * @brief Jacobian of frame EE
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_EE();

		/**
		 * @brief Time second derivative of jacobian matrix of frame EE
		 * 
		 * - depends on: {q, dq, ddq, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_EE_ddot();

		/**
		 * @brief Time derivative of jacobian matrix of frame EE
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,7> get_J_EE_dot();

		/**
		 * @brief Pseudo-Inverse of jacobian matrix of frame EE
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,6> get_J_EE_pinv();

		/**
		 * @brief Jacobian of center of mass of link 0
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_0();

		/**
		 * @brief Jacobian of center of mass of link 1
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_1();

		/**
		 * @brief Jacobian of center of mass of link 2
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_2();

		/**
		 * @brief Jacobian of center of mass of link 3
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_3();

		/**
		 * @brief Jacobian of center of mass of link 4
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_4();

		/**
		 * @brief Jacobian of center of mass of link 5
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_5();

		/**
		 * @brief Jacobian of center of mass of link 6
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_6();

		/**
		 * @brief Jacobian of center of mass of link 7
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_7();

		/**
		 * @brief Jacobian of center of mass of link 8
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,6,7> get_J_cm_8();

		/**
		 * @brief Manipulator mass matrix
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M();

		/**
		 * @brief Second time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, ddq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M_ddot();

		/**
		 * @brief Time derivative of the mass matrix
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy, par_DYN}
		 */ 
		Eigen::Matrix<double,7,7> get_M_dot();

		/**
		 * @brief relative transformation from frame-1to frame 0
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_0();

		/**
		 * @brief relative transformation from frame0to frame 1
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_1();

		/**
		 * @brief relative transformation from frame1to frame 2
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_2();

		/**
		 * @brief relative transformation from frame2to frame 3
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_3();

		/**
		 * @brief relative transformation from frame3to frame 4
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_4();

		/**
		 * @brief relative transformation from frame4to frame 5
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_5();

		/**
		 * @brief relative transformation from frame5to frame 6
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_6();

		/**
		 * @brief relative transformation from frame6to frame 7
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_7();

		/**
		 * @brief relative transformation from frame7to frame 8
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_8();

		/**
		 * @brief Template transformation of a fixed joint
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param axis Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_FIXED(Matrix<double,1,1> q_joint, Matrix<double,3,1> axis);

		/**
		 * @brief Template transformation of general prismatic joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param axis Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_P(Matrix<double,1,1> q_joint, Matrix<double,3,1> axis);

		/**
		 * @brief Template transformation of general rotoidal joint R
		 * 
		 * @param q_joint Explicit parameter
		 * 
		 * @param axis Explicit parameter
		 * 
		 * - depends on: {}
		 */ 
		Eigen::Matrix<double,4,4> get_T_JOINT_R(Matrix<double,1,1> q_joint, Matrix<double,3,1> axis);

		/**
		 * @brief absolute transformation from frame world to frame 0
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_0();

		/**
		 * @brief absolute transformation from frame world to frame 1
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_1();

		/**
		 * @brief absolute transformation from frame world to frame 2
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_2();

		/**
		 * @brief absolute transformation from frame world to frame 3
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_3();

		/**
		 * @brief absolute transformation from frame world to frame 4
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_4();

		/**
		 * @brief absolute transformation from frame world to frame 5
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_5();

		/**
		 * @brief absolute transformation from frame world to frame 6
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_6();

		/**
		 * @brief absolute transformation from frame world to frame 7
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_7();

		/**
		 * @brief absolute transformation from frame world to frame 8
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_8();

		/**
		 * @brief absolute transformation from frame world to frame EE
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,4,4> get_T_w_EE();

		/**
		 * @brief Manipulator regressor matrix
		 * 
		 * - depends on: {q, dq, dqr, ddqr, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,90> get_Yr();

		/**
		 * @brief Conversion from dynamic to regressor parameters
		 * 
		 * - depends on: {par_DYN}
		 */ 
		Eigen::Matrix<double,90,1> get_dyn2reg();

		/**
		 * @brief Kinematic parameters
		 * 
		 * - depends on: {KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,54,1> get_par_KIN();

		/**
		 * @brief Conversion from regressor to dynamic parameters
		 * 
		 * - depends on: {par_REG}
		 */ 
		Eigen::Matrix<double,90,1> get_reg2dyn();

		/**
		 * @brief Regressor matrix of term C*dqr
		 * 
		 * - depends on: {q, dq, dqr, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,90> get_reg_C();

		/**
		 * @brief Regressor matrix of term G
		 * 
		 * - depends on: {q, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,90> get_reg_G();

		/**
		 * @brief Regressor matrix of the quantity J^T*w of link EE
		 * 
		 * - depends on: {q, w, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,12> get_reg_JTw_EE();

		/**
		 * @brief Regressor matrix of the quantity J*dq of link EE
		 * 
		 * - depends on: {q, dq, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,6,12> get_reg_Jdq_EE();

		/**
		 * @brief Regressor matrix of term M*ddqr
		 * 
		 * - depends on: {q, ddqr, KIN_base_xyzrpy, KIN_EE_xyzrpy}
		 */ 
		Eigen::Matrix<double,7,90> get_reg_M();

};
#endif
