# -------------------------- #
## ----- Robot Config ----- ##
# -------------------------- #

# --- Constants --- #
PI_2: &PI_2           1.5707963267948966
PI_2_neg: &PI_2_neg  -1.5707963267948966
PI_4_neg: &PI_4_neg  -0.7853981633974483

# --- Hyperparameters --- #
num_joints: 7

# joint types: 'R' or 'P'
type_joints: 'RRRRRRR'

# # DH convention: a -> alpha -> d -> theta
DH: [0,         0,          0.3330,   0,
     0,         *PI_2_neg,  0,        0,
     0,         *PI_2,      0.3160,   0,
     0.0825,    *PI_2,      0,        0,
     -0.0825,   *PI_2_neg,  0.384,    0,
     0,         *PI_2,      0,        0,
     0.088,     *PI_2,      0.107,    0]

# gravity vector
gravity: [0, 0, -9.81]

# world to link_0
Base_to_L0:
  tr: [0, 0, 0]
  ypr: [0, 0, 0]

# Link_n to EE
Ln_to_EE:
  tr: [0, 0, 0]
  ypr: [0, 0, 0]


# -------------------------------- #
## ----- Initial Parameters ----- ##
# -------------------------------- #

# inertial parameters expressed w.r.t. DH frames
inertial:
  link1:
    mass: 4.970684
    CoM_x: 3.875e-3
    CoM_y: 2.081e-3
    CoM_z: -4.762e-2
    Ixx: 7.0337e-1
    Iyy: 7.0661e-1
    Izz: 9.1170e-3
    Ixy: -1.3900e-4
    Ixz: 6.7720e-3
    Iyz: 1.9169e-2

  link2:
    mass: 0.646926
    CoM_x: -3.141e-3
    CoM_y: -2.872e-2
    CoM_z: 3.495e-3
    Ixx: 7.9620e-3
    Iyy: 2.8110e-02
    Izz: 2.5995e-02
    Ixy: -3.9250e-3
    Ixz: 1.0254e-02
    Iyz: 7.0400e-04

  link3:
    mass: 3.228604
    CoM_x: 2.7518e-02
    CoM_y: 3.9252e-02
    CoM_z: -6.6502e-02
    Ixx: 3.7242e-02
    Iyy: 3.6155e-02
    Izz: 1.0830e-02
    Ixy: -4.7610e-03
    Ixz: -1.1396e-02
    Iyz: -1.2805e-02

  link4:
    mass: 3.587895
    CoM_x: -5.317e-02
    CoM_y: 1.04419e-01
    CoM_z: 2.7454e-02
    Ixx: 2.5853e-02
    Iyy: 1.9552e-02
    Izz: 2.8323e-02
    Ixy: 7.7960e-03
    Ixz: -1.3320e-03
    Iyz: 8.6410e-03

  link5:
    mass: 1.225946
    CoM_x: -1.1953e-02
    CoM_y: 4.1065e-02
    CoM_z: -3.8437e-02
    Ixx: 3.5549e-02
    Iyy: 2.9474e-02
    Izz: 8.6270e-03
    Ixy: -2.1170e-03
    Ixz: -4.0370e-03
    Iyz: 2.2900e-04

  link6:
    mass: 1.666555
    CoM_x: 6.0149e-02
    CoM_y: -1.4117e-02
    CoM_z: -1.0517e-02
    Ixx: 1.9640e-03
    Iyy: 4.3540e-03
    Izz: 5.4330e-03
    Ixy: 1.0900e-04
    Ixz: -1.1580e-03
    Iyz: 3.4100e-04

  link7:
    mass: 0.735522
    CoM_x: 1.0517e-02
    CoM_y: -4.252e-03
    CoM_z: 6.1597e-02
    Ixx: 1.2516e-02
    Iyy: 1.0027e-02
    Izz: 4.8150e-03
    Ixy: -4.2800e-04
    Ixz: -1.1960e-03
    Iyz: -7.4100e-04
